INSERT INTO TB_ADMIN_MENU (MENU_CODE, MENU_NAME, MENU_PATH, SORT_ORDER, USE_YN)
SELECT 'PRODUCTS', '옵션상품 관리', '/admin/products', 36, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_MENU WHERE MENU_CODE = 'PRODUCTS');

INSERT INTO TB_ADMIN_ROLE_MENU (ROLE_ID, MENU_ID, PERMISSION_ID, ALLOW_YN)
SELECT r.ROLE_ID, m.MENU_ID, p.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE r
JOIN TB_ADMIN_MENU m ON m.MENU_CODE = 'PRODUCTS'
JOIN TB_ADMIN_PERMISSION p ON p.PERMISSION_CODE = 'DESTINATION_MANAGE'
WHERE r.ROLE_CODE IN ('ADMIN', 'MASTER')
AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_MENU x WHERE x.ROLE_ID = r.ROLE_ID AND x.MENU_ID = m.MENU_ID);
