ALTER TABLE TB_TRAVEL_PRODUCT ADD (
    COURSE_TEXT CLOB,
    INCLUDED_TEXT CLOB,
    EXCLUDED_TEXT CLOB,
    USAGE_GUIDE_TEXT CLOB,
    NOTICE_TEXT CLOB,
    CANCELLATION_POLICY_TEXT CLOB,
    FAQ_TEXT CLOB,
    MEETING_TIME VARCHAR2(100 CHAR),
    MEETING_PLACE VARCHAR2(300 CHAR)
);
