-- Adds database metadata descriptions visible in Oracle database tools and USER_*_COMMENTS views.
COMMENT ON TABLE TB_USER_MSTR IS '회원 계정, 인증 수단, 프로필과 계정 상태를 관리하는 사용자 기준 테이블';
COMMENT ON COLUMN TB_USER_MSTR.USER_ID IS '회원 내부 식별자';
COMMENT ON COLUMN TB_USER_MSTR.USER_EMAIL IS '로그인 및 연락에 사용하는 회원 이메일 주소';
COMMENT ON COLUMN TB_USER_MSTR.USER_PWD IS '로컬 가입 회원의 단방향 암호화 비밀번호이며 소셜 로그인은 NULL 가능';
COMMENT ON COLUMN TB_USER_MSTR.USER_NICKNM IS '서비스 화면에 표시하는 회원 닉네임';
COMMENT ON COLUMN TB_USER_MSTR.SNS_PROVIDER IS '가입 제공자 코드로 LOCAL 또는 소셜 로그인 제공자를 구분';
COMMENT ON COLUMN TB_USER_MSTR.SNS_PROVIDER_ID IS '소셜 로그인 제공자가 발급한 외부 사용자 식별자';
COMMENT ON COLUMN TB_USER_MSTR.USER_ROLE IS '회원의 기본 역할 코드로 USER 또는 관리자 계열 역할을 저장';
COMMENT ON COLUMN TB_USER_MSTR.USER_STAT_CD IS '계정 상태 코드로 ACTIVE, SUSPENDED 등의 상태를 표현';
COMMENT ON COLUMN TB_USER_MSTR.DEL_YN IS '논리 삭제 여부로 Y는 삭제, N은 정상';
COMMENT ON COLUMN TB_USER_MSTR.USER_PHONE IS '회원 연락처 전화번호';
COMMENT ON COLUMN TB_USER_MSTR.USER_ZIPCODE IS '회원 주소의 우편번호';
COMMENT ON COLUMN TB_USER_MSTR.USER_ADDR IS '회원 기본 주소';
COMMENT ON COLUMN TB_USER_MSTR.USER_ADDR_DETAIL IS '회원 상세 주소';
COMMENT ON COLUMN TB_USER_MSTR.USER_BIRTH IS '회원 생년월일 문자열';
COMMENT ON COLUMN TB_USER_MSTR.JOIN_DT IS '회원 가입 일시';
COMMENT ON COLUMN TB_USER_MSTR.MDFY_DT IS '회원 정보 최종 수정 일시';

COMMENT ON TABLE TB_COUNTRY IS '여행 계획과 플레이스에서 사용하는 국가 기준정보 테이블';
COMMENT ON COLUMN TB_COUNTRY.COUNTRY_ID IS '국가 내부 식별자';
COMMENT ON COLUMN TB_COUNTRY.COUNTRY_NAME IS '화면에 표시하는 국가명';
COMMENT ON COLUMN TB_COUNTRY.COUNTRY_CODE IS '국가를 식별하는 고유 코드';
COMMENT ON COLUMN TB_COUNTRY.COUNTRY_STAT_CD IS '국가 사용 상태 코드로 ACTIVE 또는 INACTIVE';
COMMENT ON COLUMN TB_COUNTRY.CREATE_DT IS '국가 기준정보 등록 일시';

COMMENT ON TABLE TB_REGION IS '국가에 소속된 도시와 지역 기준정보를 관리하는 테이블';
COMMENT ON COLUMN TB_REGION.REGION_ID IS '지역 내부 식별자';
COMMENT ON COLUMN TB_REGION.COUNTRY_ID IS '지역이 소속된 국가 식별자이며 TB_COUNTRY 참조';
COMMENT ON COLUMN TB_REGION.REGION_NAME IS '화면에 표시하는 도시 또는 지역명';
COMMENT ON COLUMN TB_REGION.REGION_CODE IS '국가 내에서 고유한 지역 코드';
COMMENT ON COLUMN TB_REGION.SORT_ORDER IS '국가별 지역 노출 순서';
COMMENT ON COLUMN TB_REGION.REGION_STAT_CD IS '지역 사용 상태 코드로 ACTIVE 또는 INACTIVE';
COMMENT ON COLUMN TB_REGION.CREATE_DT IS '지역 기준정보 등록 일시';

COMMENT ON TABLE TB_DESTINATION IS '국가와 지역에 연결된 관광지, 맛집, 숙박 등 플레이스 기준정보 테이블';
COMMENT ON COLUMN TB_DESTINATION.DEST_ID IS '플레이스 내부 식별자';
COMMENT ON COLUMN TB_DESTINATION.DEST_NAME IS '플레이스명';
COMMENT ON COLUMN TB_DESTINATION.DEST_DESC IS '플레이스의 상세 소개와 설명';
COMMENT ON COLUMN TB_DESTINATION.COUNTRY_ID IS '플레이스가 속한 국가 식별자이며 TB_COUNTRY 참조';
COMMENT ON COLUMN TB_DESTINATION.REGION_ID IS '플레이스가 속한 지역 식별자이며 TB_REGION 참조';
COMMENT ON COLUMN TB_DESTINATION.CATEGORY IS '플레이스 구분 코드로 FOOD, SIGHTSEEING, SHOPPING, ACCOMMODATION, CAFE, NATURE, CULTURE, ACTIVITY';
COMMENT ON COLUMN TB_DESTINATION.IMAGE_URL IS '플레이스 대표 이미지 URL';
COMMENT ON COLUMN TB_DESTINATION.MAP_LAT IS '지도 표시용 위도';
COMMENT ON COLUMN TB_DESTINATION.MAP_LNG IS '지도 표시용 경도';
COMMENT ON COLUMN TB_DESTINATION.LIKE_COUNT IS '플레이스 좋아요 누적 수';
COMMENT ON COLUMN TB_DESTINATION.CREATE_DT IS '플레이스 등록 일시';

COMMENT ON TABLE TB_TRAVEL_PLAN IS '회원이 작성한 여행 계획의 제목, 기간, 공개 상태와 집계 정보를 저장하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_PLAN.PLAN_ID IS '여행 계획 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_PLAN.USER_ID IS '계획 작성 회원 식별자이며 탈퇴 회원 계획은 NULL 가능';
COMMENT ON COLUMN TB_TRAVEL_PLAN.USER_NICKNM IS '계획 작성 시점의 작성자 닉네임';
COMMENT ON COLUMN TB_TRAVEL_PLAN.TITLE IS '여행 계획 제목';
COMMENT ON COLUMN TB_TRAVEL_PLAN.DESCRIPTION IS '여행 계획 요약 설명';
COMMENT ON COLUMN TB_TRAVEL_PLAN.IMAGE_URL IS '여행 계획 대표 이미지 URL';
COMMENT ON COLUMN TB_TRAVEL_PLAN.TRAVEL_START_DT IS '여행 시작일';
COMMENT ON COLUMN TB_TRAVEL_PLAN.TRAVEL_END_DT IS '여행 종료일';
COMMENT ON COLUMN TB_TRAVEL_PLAN.SPOT_COUNT IS '계획에 포함된 플레이스 또는 일정 지점 수';
COMMENT ON COLUMN TB_TRAVEL_PLAN.LIKE_COUNT IS '여행 계획 좋아요 누적 수';
COMMENT ON COLUMN TB_TRAVEL_PLAN.VIEW_COUNT IS '여행 계획 조회 누적 수';
COMMENT ON COLUMN TB_TRAVEL_PLAN.IS_PUBLIC IS '공개 여부로 Y는 공개, N은 비공개';
COMMENT ON COLUMN TB_TRAVEL_PLAN.CREATE_DT IS '여행 계획 등록 일시';
COMMENT ON COLUMN TB_TRAVEL_PLAN.MDFY_DT IS '여행 계획 최종 수정 일시';

COMMENT ON TABLE TB_TRAVEL_DAY IS '여행 계획을 날짜와 일차 단위로 분리해 관리하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_DAY.DAY_ID IS '여행 일차 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_DAY.PLAN_ID IS '소속 여행 계획 식별자이며 TB_TRAVEL_PLAN 참조';
COMMENT ON COLUMN TB_TRAVEL_DAY.DAY_NO IS '여행 계획 내 일차 번호';
COMMENT ON COLUMN TB_TRAVEL_DAY.PLAN_DATE IS '해당 일차의 실제 여행 날짜';

COMMENT ON TABLE TB_TRAVEL_DAY_REGION IS '여행 일차별 방문 국가와 지역 및 지역 단위 메모를 연결하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.DAY_REGION_ID IS '일차별 방문 지역 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.DAY_ID IS '소속 여행 일차 식별자이며 TB_TRAVEL_DAY 참조';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.COUNTRY_ID IS '방문 국가 식별자이며 TB_COUNTRY 참조';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.REGION_ID IS '방문 지역 식별자이며 TB_REGION 참조';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.REGION_NOTE IS '해당 지역의 숙소나 이동 관련 메모';
COMMENT ON COLUMN TB_TRAVEL_DAY_REGION.SORT_ORDER IS '같은 일차 안에서 지역의 방문 순서';

COMMENT ON TABLE TB_TRAVEL_SCHEDULE IS '여행 일차의 지역별 세부 일정과 장소, 시간을 저장하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.SCHEDULE_ID IS '세부 일정 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.DAY_REGION_ID IS '소속 일차별 방문 지역 식별자이며 TB_TRAVEL_DAY_REGION 참조';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.SCHEDULE_TIME IS '일정 시작 시각을 HH:mm 형식으로 저장';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.TITLE IS '세부 일정 제목';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.LOCATION IS '세부 일정 장소명';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.MEMO IS '예약 정보나 주의사항 등 일정 메모';
COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.SORT_ORDER IS '같은 지역 안에서 세부 일정 노출 순서';

COMMENT ON TABLE TB_TRAVEL_TRANSPORT IS '세부 일정에 연결된 이동수단과 출발·도착 정보를 저장하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.TRANSPORT_ID IS '이동정보 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.SCHEDULE_ID IS '연결된 세부 일정 식별자이며 일정당 하나만 등록';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.TRANSPORT_TYPE IS '이동수단 코드로 TRAIN, CAR, FLIGHT, CRUISE, OTHER';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.TRANSPORT_NAME IS '항공편, 열차편, 차량 등 이동수단 명칭';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.DEPARTURE_TIME IS '출발 시각을 HH:mm 형식으로 저장';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.ARRIVAL_TIME IS '도착 시각을 HH:mm 형식으로 저장';
COMMENT ON COLUMN TB_TRAVEL_TRANSPORT.TRANSPORT_MEMO IS '좌석, 터미널, 승강장 등 이동 관련 메모';

COMMENT ON TABLE TB_TRAVEL_PACKING_ITEM IS '여행 계획별 준비물과 필수 여부를 관리하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_PACKING_ITEM.PACKING_ITEM_ID IS '준비물 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_PACKING_ITEM.PLAN_ID IS '소속 여행 계획 식별자이며 TB_TRAVEL_PLAN 참조';
COMMENT ON COLUMN TB_TRAVEL_PACKING_ITEM.ITEM_NAME IS '준비물 이름';
COMMENT ON COLUMN TB_TRAVEL_PACKING_ITEM.REQUIRED_YN IS '필수 준비물 여부로 Y는 필수, N은 선택';
COMMENT ON COLUMN TB_TRAVEL_PACKING_ITEM.SORT_ORDER IS '여행 계획 내 준비물 노출 순서';

COMMENT ON TABLE TB_ADMIN_DEPT IS '관리자 역할을 조직 단위로 분류하기 위한 운영 부서 기준 테이블';
COMMENT ON COLUMN TB_ADMIN_DEPT.DEPT_ID IS '관리자 부서 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_DEPT.DEPT_CODE IS '관리자 부서 고유 코드';
COMMENT ON COLUMN TB_ADMIN_DEPT.DEPT_NAME IS '관리자 부서명';
COMMENT ON COLUMN TB_ADMIN_DEPT.USE_YN IS '부서 사용 여부로 Y는 사용, N은 미사용';

COMMENT ON TABLE TB_ADMIN_ROLE IS '관리자 권한 등급과 소속 부서를 정의하는 역할 기준 테이블';
COMMENT ON COLUMN TB_ADMIN_ROLE.ROLE_ID IS '관리자 역할 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_ROLE.ROLE_CODE IS 'ADMIN, MASTER, SENIOR, JUNIOR 등의 고유 역할 코드';
COMMENT ON COLUMN TB_ADMIN_ROLE.ROLE_NAME IS '화면에 표시하는 관리자 역할명';
COMMENT ON COLUMN TB_ADMIN_ROLE.ROLE_LEVEL IS '권한 비교와 계층 판단에 사용하는 역할 수준 값';
COMMENT ON COLUMN TB_ADMIN_ROLE.DEPT_ID IS '역할이 속한 관리자 부서 식별자이며 TB_ADMIN_DEPT 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE.USE_YN IS '역할 사용 여부로 Y는 사용, N은 미사용';

COMMENT ON TABLE TB_ADMIN_PERMISSION IS '관리자 기능 접근과 작업 권한을 코드 단위로 정의하는 테이블';
COMMENT ON COLUMN TB_ADMIN_PERMISSION.PERMISSION_ID IS '관리자 권한 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_PERMISSION.PERMISSION_CODE IS '애플리케이션에서 검사하는 고유 권한 코드';
COMMENT ON COLUMN TB_ADMIN_PERMISSION.PERMISSION_NAME IS '관리자가 이해할 수 있는 권한명';
COMMENT ON COLUMN TB_ADMIN_PERMISSION.USE_YN IS '권한 사용 여부로 Y는 사용, N은 미사용';

COMMENT ON TABLE TB_ADMIN_MENU IS '관리자 화면의 메뉴 구조, 경로와 노출 순서를 정의하는 테이블';
COMMENT ON COLUMN TB_ADMIN_MENU.MENU_ID IS '관리자 메뉴 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_MENU.MENU_CODE IS '관리자 메뉴 고유 코드';
COMMENT ON COLUMN TB_ADMIN_MENU.MENU_NAME IS '화면에 표시하는 관리자 메뉴명';
COMMENT ON COLUMN TB_ADMIN_MENU.PARENT_MENU_ID IS '상위 메뉴 식별자이며 최상위 메뉴는 NULL';
COMMENT ON COLUMN TB_ADMIN_MENU.MENU_PATH IS '프론트엔드 관리자 화면 경로';
COMMENT ON COLUMN TB_ADMIN_MENU.SORT_ORDER IS '같은 단계에서 메뉴가 표시되는 순서';
COMMENT ON COLUMN TB_ADMIN_MENU.USE_YN IS '메뉴 사용 여부로 Y는 노출 가능, N은 미사용';

COMMENT ON TABLE TB_ADMIN_ROLE_PERMISSION IS '관리자 역할과 기능 권한의 허용 관계를 관리하는 연결 테이블';
COMMENT ON COLUMN TB_ADMIN_ROLE_PERMISSION.ROLE_PERMISSION_ID IS '역할-권한 연결 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_ROLE_PERMISSION.ROLE_ID IS '관리자 역할 식별자이며 TB_ADMIN_ROLE 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE_PERMISSION.PERMISSION_ID IS '관리자 권한 식별자이며 TB_ADMIN_PERMISSION 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE_PERMISSION.ALLOW_YN IS '해당 역할의 권한 허용 여부로 Y는 허용, N은 차단';

COMMENT ON TABLE TB_ADMIN_ROLE_MENU IS '관리자 역할별 접근 가능한 메뉴와 필요 권한을 관리하는 연결 테이블';
COMMENT ON COLUMN TB_ADMIN_ROLE_MENU.ROLE_MENU_ID IS '역할-메뉴 연결 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_ROLE_MENU.ROLE_ID IS '관리자 역할 식별자이며 TB_ADMIN_ROLE 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE_MENU.MENU_ID IS '관리자 메뉴 식별자이며 TB_ADMIN_MENU 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE_MENU.PERMISSION_ID IS '메뉴 접근에 필요한 권한 식별자이며 TB_ADMIN_PERMISSION 참조';
COMMENT ON COLUMN TB_ADMIN_ROLE_MENU.ALLOW_YN IS '해당 역할의 메뉴 접근 허용 여부로 Y는 허용, N은 차단';

COMMENT ON TABLE TB_ADMIN_USER_ROLE IS '관리자 회원에게 하나 이상의 관리자 역할을 부여하는 연결 테이블';
COMMENT ON COLUMN TB_ADMIN_USER_ROLE.USER_ROLE_ID IS '사용자-역할 연결 내부 식별자';
COMMENT ON COLUMN TB_ADMIN_USER_ROLE.USER_ID IS '관리자 회원 식별자이며 TB_USER_MSTR 참조';
COMMENT ON COLUMN TB_ADMIN_USER_ROLE.ROLE_ID IS '부여된 관리자 역할 식별자이며 TB_ADMIN_ROLE 참조';
COMMENT ON COLUMN TB_ADMIN_USER_ROLE.PRIMARY_YN IS '여러 역할 중 대표 역할 여부로 Y는 대표 역할';

COMMENT ON TABLE TB_DEST_RECOMMEND IS '홈 화면 등에 노출할 추천 플레이스와 노출 기간 및 순서를 관리하는 테이블';
COMMENT ON COLUMN TB_DEST_RECOMMEND.RECOMMEND_ID IS '추천 설정 내부 식별자';
COMMENT ON COLUMN TB_DEST_RECOMMEND.DEST_ID IS '추천 대상으로 지정한 플레이스 식별자이며 TB_DESTINATION 참조';
COMMENT ON COLUMN TB_DEST_RECOMMEND.DISPLAY_START_DT IS '추천 노출 시작 일시';
COMMENT ON COLUMN TB_DEST_RECOMMEND.DISPLAY_END_DT IS '추천 노출 종료 일시';
COMMENT ON COLUMN TB_DEST_RECOMMEND.SORT_ORDER IS '추천 영역 내 노출 순서';
COMMENT ON COLUMN TB_DEST_RECOMMEND.USE_YN IS '추천 설정 사용 여부로 Y는 사용, N은 미사용';
COMMENT ON COLUMN TB_DEST_RECOMMEND.IMAGE_URL IS '추천 영역에서 별도로 사용할 대표 이미지 URL';

COMMENT ON TABLE TB_TRAVEL_PRODUCT IS '플레이스에 연결된 입장권, 투어, 패스 등 예약 가능한 여행 상품 테이블';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRODUCT_ID IS '여행 상품 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.DEST_ID IS '상품이 연결된 플레이스 식별자이며 TB_DESTINATION 참조';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRODUCT_NAME IS '고객에게 표시하는 여행 상품명';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRODUCT_SUMMARY IS '상품 목록과 카드에 표시하는 한 줄 요약';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRODUCT_TYPE IS '상품 유형 코드로 TICKET, TOUR, PASS, ACTIVITY, TRANSPORT, ETC';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PROVIDER_NAME IS '상품을 판매하거나 제공하는 업체명';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRODUCT_DESC IS '상품의 전체 상세 설명';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.IMAGE_URL IS '상품 대표 이미지 URL';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.DETAIL_IMAGE_URL IS '상품 상세 설명에 표시하는 이미지 URL';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.BOOKING_URL IS '외부 판매처 또는 예약 페이지 URL';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.PRICE IS '상품 기본 판매 가격';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.CURRENCY IS 'ISO 4217 형식의 통화 코드';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.USE_YN IS '상품 판매 및 노출 여부로 Y는 사용, N은 미사용';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.SORT_ORDER IS '같은 플레이스 내 상품 노출 순서';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.CREATE_DT IS '여행 상품 등록 일시';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.COURSE_TEXT IS '투어 이동 경로와 시간대별 코스 설명';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.INCLUDED_TEXT IS '상품 가격에 포함되는 서비스와 혜택';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.EXCLUDED_TEXT IS '상품 가격에 포함되지 않는 항목';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.USAGE_GUIDE_TEXT IS '예약 후 상품을 사용하는 방법과 절차';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.NOTICE_TEXT IS '예약과 이용 전에 확인할 주의사항';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.CANCELLATION_POLICY_TEXT IS '상품 취소 및 환불 규정';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.FAQ_TEXT IS '상품 관련 자주 묻는 질문과 답변';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.MEETING_TIME IS '투어 또는 액티비티 집합 시간 안내';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT.MEETING_PLACE IS '투어 또는 액티비티 미팅 장소 안내';

COMMENT ON TABLE TB_TRAVEL_PRODUCT_OPTION IS '여행 상품의 가격, 유효기간, 확정 방식이 다른 판매 옵션을 관리하는 테이블';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.OPTION_ID IS '상품 옵션 내부 식별자';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.PRODUCT_ID IS '소속 여행 상품 식별자이며 TB_TRAVEL_PRODUCT 참조';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.OPTION_NAME IS '고객에게 표시하는 상품 옵션명';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.OPTION_DESC IS '상품 옵션의 구성과 차이를 설명하는 문구';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.PRICE IS '해당 옵션의 판매 가격';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.CURRENCY IS 'ISO 4217 형식의 옵션 가격 통화 코드';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.CANCELLATION_POLICY IS '해당 옵션에 적용되는 취소 및 환불 정책';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.VALIDITY_TEXT IS '옵션의 사용 가능 기간 또는 유효 조건';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.CONFIRMATION_TYPE IS '예약 확정 방식으로 INSTANT 등 확정 유형을 저장';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.USE_YN IS '옵션 판매 및 노출 여부로 Y는 사용, N은 미사용';
COMMENT ON COLUMN TB_TRAVEL_PRODUCT_OPTION.SORT_ORDER IS '같은 상품 내 옵션 노출 순서';

