ALTER TABLE TB_TRAVEL_SCHEDULE ADD (PRODUCT_ORDER_ID NUMBER(19));

ALTER TABLE TB_TRAVEL_SCHEDULE
    ADD CONSTRAINT FK_SCHEDULE_PRODUCT_ORDER
        FOREIGN KEY (PRODUCT_ORDER_ID) REFERENCES TB_PRODUCT_ORDER (ORDER_ID);

CREATE INDEX IX_SCHEDULE_PRODUCT_ORDER ON TB_TRAVEL_SCHEDULE (PRODUCT_ORDER_ID);

COMMENT ON COLUMN TB_TRAVEL_SCHEDULE.PRODUCT_ORDER_ID IS '일정에 연동한 회원 옵션상품 예약 식별자이며 TB_PRODUCT_ORDER 참조';
