CREATE TABLE TB_STORED_IMAGE (
    IMAGE_ID VARCHAR2(36 CHAR) NOT NULL,
    CATEGORY VARCHAR2(30 CHAR) NOT NULL,
    RELATIVE_PATH VARCHAR2(500 CHAR) NOT NULL,
    CONTENT_TYPE VARCHAR2(50 CHAR) NOT NULL,
    FILE_SIZE NUMBER(19) NOT NULL,
    CREATE_DT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_STORED_IMAGE PRIMARY KEY (IMAGE_ID),
    CONSTRAINT UK_STORED_IMAGE_PATH UNIQUE (RELATIVE_PATH)
);
COMMENT ON TABLE TB_STORED_IMAGE IS 'NAS 이미지 파일 저장 위치';
COMMENT ON COLUMN TB_STORED_IMAGE.IMAGE_ID IS '이미지 식별자';
COMMENT ON COLUMN TB_STORED_IMAGE.CATEGORY IS '이미지 용도';
COMMENT ON COLUMN TB_STORED_IMAGE.RELATIVE_PATH IS 'NAS 루트 기준 상대 경로';
COMMENT ON COLUMN TB_STORED_IMAGE.CONTENT_TYPE IS '검증된 이미지 형식';
COMMENT ON COLUMN TB_STORED_IMAGE.FILE_SIZE IS '파일 크기 바이트';
COMMENT ON COLUMN TB_STORED_IMAGE.CREATE_DT IS '업로드 일시';
