INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD, CREATE_DT)
SELECT COUNTRY_ID, '푸꾸옥', 'PQC', 4, 'ACTIVE', SYSTIMESTAMP
FROM TB_COUNTRY
WHERE COUNTRY_CODE = 'VN'
  AND NOT EXISTS (
      SELECT 1
      FROM TB_REGION r
      WHERE r.COUNTRY_ID = TB_COUNTRY.COUNTRY_ID
        AND r.REGION_CODE = 'PQC'
  );
