spring:
  application:
    name: routemate

  thymeleaf:
    cache: false

  jpa:
    open-in-view: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mysql}

app:
  seed:
    enabled: ${APP_SEED_ENABLED:false}
