spring:
  application:
    name: routemate

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 테이블 구조 자동 반영
    show-sql: true     # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # 🔥 한 줄로 길게 나오는 SQL을 이쁘게 줄바꿈 정렬해 줍니다.
        highlight_sql: true # 🔥 SQL 키워드(SELECT, INSERT 등)에 색상을 입혀 가독성을 높입니다.

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    username: routemate
    password: 1234

server:
  port: 8090