import { ImageUpload } from '../../components/ImageUpload';
import { useCallback, useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import axios from 'axios';
import { api } from '../../lib/http';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { SearchableSelect } from '../../components/SearchableSelect';
import { StyledSelect } from '../../components/StyledSelect';
import { useAuth } from '../../hooks/useAuth';

type UseYn = 'Y' | 'N';
type Place = { destinationId: number; destName: string; countryName: string; regionName: string };
type ProductOption = { optionId?: number; optionName: string; optionDesc: string; price: string; currency: string; cancellationPolicy: string; validityText: string; confirmationType: string; useYn: UseYn; sortOrder: string };
type Product = { productId: number; destinationId: number; destinationName: string; countryName: string; regionName: string; productName: string; productSummary: string | null; productType: string; productDesc: string | null; imageUrl: string | null; detailImageUrl: string | null; courseText: string | null; includedText: string | null; excludedText: string | null; usageGuideText: string | null; noticeText: string | null; cancellationPolicyText: string | null; faqText: string | null; meetingTime: string | null; meetingPlace: string | null; bookingUrl: string | null; price: number; currency: string; useYn: UseYn; sortOrder: number; approvalStatus: string; options: Array<Omit<ProductOption, 'price' | 'sortOrder'> & { price: number; sortOrder: number }> };
type Form = { destinationId: string; productName: string; productSummary: string; productType: string; productDesc: string; imageUrl: string; detailImageUrl: string; courseText: string; includedText: string; excludedText: string; usageGuideText: string; noticeText: string; cancellationPolicyText: string; faqText: string; meetingTime: string; meetingPlace: string; bookingUrl: string; price: string; currency: string; useYn: UseYn; sortOrder: string; options: ProductOption[] };

const fieldClass = 'h-11 rounded-xl border border-white/10 bg-slate-950/70 px-3 text-sm text-white outline-none transition focus:border-indigo-400/50 focus:ring-2 focus:ring-indigo-400/10';
const emptyOption = (): ProductOption => ({ optionName: '', optionDesc: '', price: '0', currency: 'KRW', cancellationPolicy: '취소 및 환불 정책을 입력하세요.', validityText: '지정일에 한해 유효', confirmationType: 'INSTANT', useYn: 'Y', sortOrder: '1' });
const emptyForm = (): Form => ({ destinationId: '', productName: '', productSummary: '', productType: 'TICKET', productDesc: '', imageUrl: '', detailImageUrl: '', courseText: '', includedText: '', excludedText: '', usageGuideText: '', noticeText: '', cancellationPolicyText: '', faqText: '', meetingTime: '', meetingPlace: '', bookingUrl: '', price: '0', currency: 'KRW', useYn: 'Y', sortOrder: '1', options: [emptyOption()] });
const productTypes = [{ value: 'TICKET', label: '입장권·패스', icon: 'fa-ticket' }, { value: 'TOUR', label: '투어·액티비티', icon: 'fa-person-hiking' }, { value: 'TRANSFER', label: '공항·교통', icon: 'fa-car' }, { value: 'SIM', label: 'eSIM·통신', icon: 'fa-sim-card' }, { value: 'ETC', label: '기타', icon: 'fa-box' }];

/**
 * 파트너사가 자기 회사의 옵션 상품과 판매 옵션을 등록·수정하는 화면이다.
 *
 * 새 상품은 승인 대기 상태로 저장되며, 다른 파트너사의 상품은 API와 화면 모두에서 접근할 수 없다.
 */
export const PartnerProductManagement = () => {
  const { user, loading, logout } = useAuth();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [products, setProducts] = useState<Product[]>([]);
  const [places, setPlaces] = useState<Place[]>([]);
  const [form, setForm] = useState<Form>(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [busy, setBusy] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setBusy(true);
    try {
      const [productResponse, placeResponse] = await Promise.all([
        api.get<Product[]>('/api/partner/products'),
        api.get<Place[]>('/api/partner/destinations/places'),
      ]);
      setProducts(productResponse.data);
      setPlaces(placeResponse.data);
    } catch (loadError) {
      setError(axios.isAxiosError(loadError) ? loadError.response?.data?.detail ?? '상품 정보를 불러오지 못했습니다.' : '상품 정보를 불러오지 못했습니다.');
    } finally { setBusy(false); }
  }, []);

  useEffect(() => {
    if (!loading && user?.userRole !== 'PARTNER_OWNER') navigate('/partner/login', { replace: true });
  }, [loading, navigate, user]);
  useEffect(() => { if (user?.userRole === 'PARTNER_OWNER') void load(); }, [load, user]);

  const openCreate = () => { setForm(emptyForm()); setEditingId(null); setError(null); setShowForm(true); };
  const openEdit = (product: Product) => {
    setEditingId(product.productId);
    setForm({ destinationId: String(product.destinationId), productName: product.productName, productSummary: product.productSummary ?? '', productType: product.productType, productDesc: product.productDesc ?? '', imageUrl: product.imageUrl ?? '', detailImageUrl: product.detailImageUrl ?? '', courseText: product.courseText ?? '', includedText: product.includedText ?? '', excludedText: product.excludedText ?? '', usageGuideText: product.usageGuideText ?? '', noticeText: product.noticeText ?? '', cancellationPolicyText: product.cancellationPolicyText ?? '', faqText: product.faqText ?? '', meetingTime: product.meetingTime ?? '', meetingPlace: product.meetingPlace ?? '', bookingUrl: product.bookingUrl ?? '', price: String(product.price), currency: product.currency, useYn: product.useYn, sortOrder: String(product.sortOrder), options: product.options.length ? product.options.map((option) => ({ ...option, price: String(option.price), sortOrder: String(option.sortOrder) })) : [emptyOption()] });
    setError(null); setShowForm(true);
  };
  useEffect(() => {
    const productId = Number(searchParams.get('edit'));
    const product = products.find((item) => item.productId === productId);
    if (product && !showForm) {
      openEdit(product);
      navigate('/partner/products', { replace: true });
    }
  }, [navigate, products, searchParams, showForm]);
  const updateOption = (index: number, patch: Partial<ProductOption>) => setForm((current) => ({ ...current, options: current.options.map((option, optionIndex) => optionIndex === index ? { ...option, ...patch } : option) }));


  const textArea = (label: string, key: keyof Form, placeholder: string, rows = 4) => <label className="grid gap-2 text-xs font-semibold text-slate-400">{label}<textarea required={key === 'productDesc'} rows={rows} value={String(form[key])} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} placeholder={placeholder} className="rounded-xl border border-white/10 bg-slate-950/70 px-3 py-3 text-sm leading-6 text-white outline-none transition focus:border-indigo-400/50 focus:ring-2 focus:ring-indigo-400/10" /></label>;
  const save = async (event: FormEvent) => {
    event.preventDefault(); if (uploadingImage) return;
    if (!form.destinationId) { setError('연결할 여행지를 선택하세요.'); return; }
    if (!form.productSummary.trim() || !form.productDesc.trim()) { setError('상품 요약과 상세 설명을 입력하세요.'); return; }
    if (form.options.some((option) => !option.optionName.trim())) { setError('모든 패키지 옵션의 이름을 입력하세요.'); return; }
    const payload = { ...form, destinationId: Number(form.destinationId), price: Number(form.price), currency: form.currency.toUpperCase(), sortOrder: Number(form.sortOrder), options: form.options.map((option) => ({ ...option, price: Number(option.price), currency: option.currency.toUpperCase(), sortOrder: Number(option.sortOrder) })) };
    setSaving(true); setError(null);
    try {
      if (editingId) await api.patch(`/api/partner/products/${editingId}`, payload);
      else await api.post('/api/partner/products', payload);
      setShowForm(false); setEditingId(null); setForm(emptyForm()); await load();
    } catch (saveError) {
      setError(axios.isAxiosError(saveError) ? saveError.response?.data?.detail ?? '상품을 저장하지 못했습니다.' : '상품을 저장하지 못했습니다.');
    } finally { setSaving(false); }
  };

  return <main className="min-h-screen flex-grow bg-slate-950 px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-start sm:justify-between"><div><Link to="/partner" className="text-sm font-bold text-indigo-300">RouteMate Partner</Link><p className="mt-5 text-xs font-bold tracking-[0.2em] text-indigo-300">PARTNER PRODUCT MANAGEMENT</p><h1 className="mt-2 text-3xl font-extrabold">옵션상품 관리</h1><p className="mt-2 text-sm text-slate-500">상품 정보와 패키지 옵션을 등록하면 관리자 검토 후 고객에게 노출됩니다.</p><nav className="mt-4 flex gap-4 text-sm font-semibold text-slate-400"><Link to="/partner" className="hover:text-indigo-200">대시보드</Link><Link to="/partner/products" className="text-indigo-300">옵션상품관리</Link><Link to="/partner/staff" className="hover:text-indigo-200">직원 관리</Link></nav></div><div className="flex gap-2"><button type="button" onClick={() => void logout().then(() => navigate('/partner/login'))} className="rounded-xl border border-white/10 px-3 py-2.5 text-xs font-bold text-slate-300">로그아웃</button><button type="button" onClick={openCreate} className="rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-indigo-500/20"><i className="fa-solid fa-plus mr-2" />상품 등록</button></div></header>
    {error ? <p role="alert" className="mt-5 rounded-2xl border border-rose-400/15 bg-rose-400/5 px-4 py-3 text-sm text-rose-200">{error}</p> : null}
    <section className="mt-7 rounded-[24px] border border-white/10 bg-white/[0.03] p-5"><p className="text-xs font-bold tracking-[0.16em] text-indigo-300">MY PRODUCT CATALOG</p><p className="mt-1 text-sm text-slate-500">내 파트너사에 귀속된 상품 {products.length}개</p></section>
    <section className="mt-4 overflow-hidden rounded-[24px] border border-white/10 bg-white/[0.03]">{busy ? <div className="flex min-h-[260px] items-center justify-center text-sm text-slate-500"><i className="fa-solid fa-spinner fa-spin mr-2" />상품을 불러오는 중...</div> : <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="border-b border-white/10 bg-black/10 text-[11px] text-slate-600"><tr><th className="px-6 py-4">상품</th><th className="px-4 py-4">연결 여행지</th><th className="px-4 py-4">패키지</th><th className="px-4 py-4">최저가</th><th className="px-4 py-4">검토 상태</th><th className="px-6 py-4 text-right">관리</th></tr></thead><tbody className="divide-y divide-white/5">{products.map((product) => <tr key={product.productId} className="hover:bg-white/[0.02]"><td className="px-6 py-4"><div className="flex items-center gap-3">{product.imageUrl ? <img src={product.imageUrl} alt="" className="h-11 w-16 rounded-lg object-cover" /> : <span className="flex h-11 w-16 items-center justify-center rounded-lg bg-indigo-500/10 text-indigo-300"><i className="fa-solid fa-ticket" /></span>}<div><p className="text-sm font-semibold text-slate-200">{product.productName}</p><p className="mt-1 max-w-[260px] truncate text-xs text-slate-600">{product.productSummary || '상품 요약 없음'}</p></div></div></td><td className="px-4 py-4"><p className="text-sm text-slate-300">{product.destinationName}</p><p className="mt-1 text-xs text-slate-600">{product.countryName} · {product.regionName}</p></td><td className="px-4 py-4 text-xs text-slate-400">{product.options.length}개 옵션</td><td className="px-4 py-4 text-sm font-bold text-indigo-200">{Math.min(product.price, ...product.options.map((option) => option.price)).toLocaleString('ko-KR')} {product.currency}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${product.approvalStatus === 'APPROVED' ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-200'}`}>{product.approvalStatus === 'APPROVED' ? '승인 완료' : '검토 대기'}</span></td><td className="px-6 py-4 text-right"><button type="button" onClick={() => openEdit(product)} className="text-xs font-semibold text-indigo-300">수정</button></td></tr>)}{products.length === 0 ? <tr><td colSpan={6} className="px-6 py-16 text-center text-sm text-slate-600">등록된 옵션상품이 없습니다. 첫 상품을 등록해 보세요.</td></tr> : null}</tbody></table></div>}</section>
    {showForm ? <div role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) setShowForm(false); }} className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/75 px-4 py-6 backdrop-blur-sm"><section role="dialog" aria-modal="true" className="my-auto w-full max-w-5xl rounded-[28px] border border-white/10 bg-slate-900 p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.18em] text-indigo-300">PRODUCT BUILDER</p><h2 className="mt-2 text-xl font-extrabold">{editingId ? '옵션상품 수정' : '옵션상품 구성'}</h2><p className="mt-2 text-xs leading-5 text-slate-500">파트너사 상품은 저장 후 관리자 승인 절차를 거칩니다.</p></div><button type="button" disabled={saving} onClick={() => setShowForm(false)} className="flex h-9 w-9 items-center justify-center rounded-xl text-slate-500 hover:bg-white/5 hover:text-white"><i className="fa-solid fa-xmark" /></button></div><form onSubmit={(event) => void save(event)} className="mt-7 grid gap-5"><section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">01 · 기본 정보</p><div className="mt-4 grid gap-4"><label className="grid gap-2 text-xs font-semibold text-slate-400">연결 여행지<SearchableSelect value={form.destinationId} options={places.map((place) => ({ value: String(place.destinationId), label: place.destName, hint: `${place.countryName} · ${place.regionName}` }))} placeholder="여행지를 검색하세요" onChange={(value) => setForm((current) => ({ ...current, destinationId: value }))} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs font-semibold text-slate-400">상품명<input required maxLength={150} value={form.productName} onChange={(event) => setForm((current) => ({ ...current, productName: event.target.value }))} placeholder="예: 유니버설 스튜디오 재팬 1일 패스" className={fieldClass} /></label><label className="grid gap-2 text-xs font-semibold text-slate-400">상품 유형<StyledSelect value={form.productType} onChange={(value) => setForm((current) => ({ ...current, productType: value }))} ariaLabel="상품 유형" options={productTypes} /></label></div></div></section>
      <section className="rounded-2xl border border-indigo-400/15 bg-indigo-500/[0.04] p-4"><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">02 · 상품 소개</p><div className="mt-4 grid gap-4">{textArea('상품 한줄 요약', 'productSummary', '고객이 바로 이해할 수 있는 한 문장', 2)}{textArea('상품 상세 설명', 'productDesc', '상품 특징, 추천 대상, 포함 혜택을 자세히 작성하세요.', 7)}{textArea('코스·일정', 'courseText', '예: 오전 입장 → 주요 어트랙션 → 자유 관람', 4)}</div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">03 · 포함·이용 안내</p><div className="mt-4 grid gap-4 md:grid-cols-2">{textArea('포함 사항', 'includedText', '포함 내용을 줄바꿈으로 입력')}{textArea('불포함 사항', 'excludedText', '불포함 내용을 입력')}{textArea('이용 안내', 'usageGuideText', '이용 시간과 바우처 사용법')}{textArea('필수 확인 사항', 'noticeText', '연령 제한, 노쇼, 날씨 등')}{textArea('취소·환불 정책', 'cancellationPolicyText', '무료 취소 기준과 환불 불가 조건')}{textArea('자주 묻는 질문(FAQ)', 'faqText', '질문과 답변을 줄바꿈으로 입력')}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs font-semibold text-slate-400">만나는 시간<input value={form.meetingTime} onChange={(event) => setForm((current) => ({ ...current, meetingTime: event.target.value }))} placeholder="예: 08:00 또는 예약 하루 전 안내" className={fieldClass} /></label><label className="grid gap-2 text-xs font-semibold text-slate-400">만나는 장소<input value={form.meetingPlace} onChange={(event) => setForm((current) => ({ ...current, meetingPlace: event.target.value }))} placeholder="예: 오사카역 중앙 개찰구" className={fieldClass} /></label></div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">04 · 이미지 및 예약</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><ImageUpload value={form.imageUrl} endpoint="/api/partner/products/images" disabled={saving || uploadingImage} onUploadingChange={setUploadingImage} onChange={(imageUrl) => setForm((current) => ({ ...current, imageUrl }))} /><ImageUpload label="상품 설명 이미지" value={form.detailImageUrl} endpoint="/api/partner/products/images?detail=true" disabled={saving || uploadingImage} onUploadingChange={setUploadingImage} onChange={(detailImageUrl) => setForm((current) => ({ ...current, detailImageUrl }))} /></div><label className="mt-4 grid gap-2 text-xs font-semibold text-slate-400">예약 링크<input type="url" value={form.bookingUrl} onChange={(event) => setForm((current) => ({ ...current, bookingUrl: event.target.value }))} placeholder="https://partner.example/..." className={fieldClass} /></label></section>
      <section className="rounded-2xl border border-indigo-400/15 bg-indigo-500/[0.04] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">05 · 패키지 옵션</p><p className="mt-1 text-xs text-slate-500">상품 안에 여러 판매 조건과 가격을 구성합니다.</p></div><button type="button" onClick={() => setForm((current) => ({ ...current, options: [...current.options, { ...emptyOption(), sortOrder: String(current.options.length + 1) }] }))} className="rounded-xl border border-indigo-400/25 bg-indigo-500/10 px-3 py-2 text-xs font-bold text-indigo-200"><i className="fa-solid fa-plus mr-1" />옵션 추가</button></div><div className="mt-4 grid gap-3">{form.options.map((option, index) => <div key={`${option.optionId ?? 'new'}-${index}`} className="rounded-2xl border border-white/10 bg-slate-950/45 p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-300">패키지 {index + 1}</p>{form.options.length > 1 ? <button type="button" onClick={() => setForm((current) => ({ ...current, options: current.options.filter((_, optionIndex) => optionIndex !== index) }))} className="text-xs text-rose-300">삭제</button> : null}</div><div className="mt-3 grid gap-3 md:grid-cols-[1.5fr_1fr_130px]"><input required value={option.optionName} onChange={(event) => updateOption(index, { optionName: event.target.value })} placeholder="예: 성인 1일 스튜디오 패스" className={fieldClass} /><input value={option.optionDesc} onChange={(event) => updateOption(index, { optionDesc: event.target.value })} placeholder="옵션 설명" className={fieldClass} /><input required min="0" type="number" value={option.price} onChange={(event) => updateOption(index, { price: event.target.value })} placeholder="가격" className={fieldClass} /></div><div className="mt-3 grid gap-3 md:grid-cols-3"><input value={option.validityText} onChange={(event) => updateOption(index, { validityText: event.target.value })} placeholder="유효기간" className={fieldClass} /><input value={option.cancellationPolicy} onChange={(event) => updateOption(index, { cancellationPolicy: event.target.value })} placeholder="취소·환불 정책" className={fieldClass} /><StyledSelect value={option.confirmationType} onChange={(value) => updateOption(index, { confirmationType: value })} ariaLabel="확정 방식" options={[{ value: 'INSTANT', label: '예약 즉시 확정', icon: 'fa-bolt' }, { value: 'MANUAL', label: '예약 후 확인', icon: 'fa-clock' }]} /></div></div>)}</div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><p className="text-xs font-bold tracking-[0.14em] text-indigo-300">06 · 판매 설정</p><div className="mt-4 grid gap-4 sm:grid-cols-4"><label className="grid gap-2 text-xs font-semibold text-slate-400">기본 가격<input required min="0" type="number" value={form.price} onChange={(event) => setForm((current) => ({ ...current, price: event.target.value }))} className={fieldClass} /></label><label className="grid gap-2 text-xs font-semibold text-slate-400">통화<input required maxLength={3} value={form.currency} onChange={(event) => setForm((current) => ({ ...current, currency: event.target.value.toUpperCase() }))} className={`${fieldClass} uppercase`} /></label><label className="grid gap-2 text-xs font-semibold text-slate-400">노출 순서<input min={1} type="number" value={form.sortOrder} onChange={(event) => setForm((current) => ({ ...current, sortOrder: event.target.value }))} className={fieldClass} /></label><label className="grid gap-2 text-xs font-semibold text-slate-400">판매 상태<StyledSelect value={form.useYn} onChange={(value) => setForm((current) => ({ ...current, useYn: value as UseYn }))} ariaLabel="판매 상태" options={[{ value: 'Y', label: '판매중', icon: 'fa-circle-check' }, { value: 'N', label: '비활성', icon: 'fa-circle-pause' }]} /></label></div></section>
      <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={saving || uploadingImage} onClick={() => setShowForm(false)} className="h-11 rounded-xl border border-white/10 px-5 text-sm font-semibold text-slate-400 hover:bg-white/5 hover:text-white">취소</button><button type="submit" disabled={saving || uploadingImage} className="h-11 rounded-xl bg-indigo-500 px-6 text-sm font-bold text-white shadow-lg shadow-indigo-500/20 disabled:opacity-50">{saving ? '저장 중...' : uploadingImage ? '이미지 업로드 중...' : editingId ? '수정 저장' : '상품 등록'}</button></div></form></section></div> : null}
  </div></main>;
};
