ALTER TABLE TB_REGION
    ADD CONSTRAINT UK_REGION_ID_COUNTRY UNIQUE (REGION_ID, COUNTRY_ID);

ALTER TABLE TB_DESTINATION
    ADD CONSTRAINT FK_DEST_REGION_COUNTRY
        FOREIGN KEY (REGION_ID, COUNTRY_ID)
        REFERENCES TB_REGION (REGION_ID, COUNTRY_ID);
