CREATE TABLE TB_TRAVEL_PRODUCT (
    PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT,
    DEST_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(150) NOT NULL,
    PRODUCT_TYPE VARCHAR(30) NOT NULL,
    PROVIDER_NAME VARCHAR(100),
    PRODUCT_DESC LONGTEXT,
    IMAGE_URL VARCHAR(500),
    BOOKING_URL VARCHAR(1000),
    PRICE DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) NOT NULL DEFAULT 'KRW',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    SORT_ORDER INT NOT NULL DEFAULT 1,
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_TRAVEL_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_DEST FOREIGN KEY (DEST_ID) REFERENCES TB_DESTINATION (DEST_ID),
    CONSTRAINT CK_PRODUCT_USE CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_PRODUCT_DEST_USE_SORT ON TB_TRAVEL_PRODUCT (DEST_ID, USE_YN, SORT_ORDER);
