ALTER TABLE TB_TRAVEL_PRODUCT
    ADD COLUMN COURSE_TEXT LONGTEXT NULL,
    ADD COLUMN INCLUDED_TEXT LONGTEXT NULL,
    ADD COLUMN EXCLUDED_TEXT LONGTEXT NULL,
    ADD COLUMN USAGE_GUIDE_TEXT LONGTEXT NULL,
    ADD COLUMN NOTICE_TEXT LONGTEXT NULL,
    ADD COLUMN CANCELLATION_POLICY_TEXT LONGTEXT NULL,
    ADD COLUMN FAQ_TEXT LONGTEXT NULL,
    ADD COLUMN MEETING_TIME VARCHAR(100) NULL,
    ADD COLUMN MEETING_PLACE VARCHAR(300) NULL;
