CREATE TABLE TB_TRAVEL_PRODUCT_OPTION (
    OPTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    OPTION_NAME VARCHAR(150) NOT NULL,
    OPTION_DESC VARCHAR(500),
    PRICE DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CURRENCY VARCHAR(3) NOT NULL DEFAULT 'KRW',
    CANCELLATION_POLICY VARCHAR(500),
    VALIDITY_TEXT VARCHAR(200),
    CONFIRMATION_TYPE VARCHAR(20) NOT NULL DEFAULT 'INSTANT',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    SORT_ORDER INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_TRAVEL_PRODUCT_OPTION PRIMARY KEY (OPTION_ID),
    CONSTRAINT FK_PRODUCT_OPTION_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_TRAVEL_PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PRODUCT_OPTION_USE CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_PRODUCT_OPTION_PRICE CHECK (PRICE >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_PRODUCT_OPTION_PRODUCT_SORT ON TB_TRAVEL_PRODUCT_OPTION (PRODUCT_ID, SORT_ORDER);
