-- Adds database metadata descriptions visible in MySQL Workbench, DataGrip and INFORMATION_SCHEMA.
-- Column definitions are repeated because MySQL stores column comments through MODIFY COLUMN.
ALTER TABLE TB_USER_MSTR COMMENT = '회원 계정, 인증 수단, 프로필과 계정 상태를 관리하는 사용자 기준 테이블';
ALTER TABLE TB_USER_MSTR
    MODIFY COLUMN USER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원 내부 식별자',
    MODIFY COLUMN USER_EMAIL VARCHAR(100) NOT NULL COMMENT '로그인 및 연락에 사용하는 회원 이메일 주소',
    MODIFY COLUMN USER_PWD VARCHAR(255) NULL COMMENT '로컬 가입 회원의 단방향 암호화 비밀번호이며 소셜 로그인은 NULL 가능',
    MODIFY COLUMN USER_NICKNM VARCHAR(50) NOT NULL COMMENT '서비스 화면에 표시하는 회원 닉네임',
    MODIFY COLUMN SNS_PROVIDER VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT '가입 제공자 코드로 LOCAL 또는 소셜 로그인 제공자를 구분',
    MODIFY COLUMN SNS_PROVIDER_ID VARCHAR(100) NULL COMMENT '소셜 로그인 제공자가 발급한 외부 사용자 식별자',
    MODIFY COLUMN USER_ROLE VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '회원의 기본 역할 코드로 USER 또는 관리자 계열 역할을 저장',
    MODIFY COLUMN USER_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '계정 상태 코드로 ACTIVE, SUSPENDED 등의 상태를 표현',
    MODIFY COLUMN DEL_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부로 Y는 삭제, N은 정상',
    MODIFY COLUMN USER_PHONE VARCHAR(20) NULL COMMENT '회원 연락처 전화번호',
    MODIFY COLUMN USER_ZIPCODE VARCHAR(10) NULL COMMENT '회원 주소의 우편번호',
    MODIFY COLUMN USER_ADDR VARCHAR(200) NULL COMMENT '회원 기본 주소',
    MODIFY COLUMN USER_ADDR_DETAIL VARCHAR(200) NULL COMMENT '회원 상세 주소',
    MODIFY COLUMN USER_BIRTH VARCHAR(10) NULL COMMENT '회원 생년월일 문자열',
    MODIFY COLUMN JOIN_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '회원 가입 일시',
    MODIFY COLUMN MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '회원 정보 최종 수정 일시';

ALTER TABLE TB_COUNTRY COMMENT = '여행 계획과 플레이스에서 사용하는 국가 기준정보 테이블';
ALTER TABLE TB_COUNTRY
    MODIFY COLUMN COUNTRY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '국가 내부 식별자',
    MODIFY COLUMN COUNTRY_NAME VARCHAR(50) NOT NULL COMMENT '화면에 표시하는 국가명',
    MODIFY COLUMN COUNTRY_CODE VARCHAR(10) NOT NULL COMMENT '국가를 식별하는 고유 코드',
    MODIFY COLUMN COUNTRY_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '국가 사용 상태 코드로 ACTIVE 또는 INACTIVE',
    MODIFY COLUMN CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '국가 기준정보 등록 일시';

ALTER TABLE TB_REGION COMMENT = '국가에 소속된 도시와 지역 기준정보를 관리하는 테이블';
ALTER TABLE TB_REGION
    MODIFY COLUMN REGION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '지역 내부 식별자',
    MODIFY COLUMN COUNTRY_ID BIGINT NOT NULL COMMENT '지역이 소속된 국가 식별자이며 TB_COUNTRY 참조',
    MODIFY COLUMN REGION_NAME VARCHAR(50) NOT NULL COMMENT '화면에 표시하는 도시 또는 지역명',
    MODIFY COLUMN REGION_CODE VARCHAR(20) NOT NULL COMMENT '국가 내에서 고유한 지역 코드',
    MODIFY COLUMN SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '국가별 지역 노출 순서',
    MODIFY COLUMN REGION_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '지역 사용 상태 코드로 ACTIVE 또는 INACTIVE',
    MODIFY COLUMN CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '지역 기준정보 등록 일시';

ALTER TABLE TB_DESTINATION COMMENT = '국가와 지역에 연결된 관광지, 맛집, 숙박 등 플레이스 기준정보 테이블';
ALTER TABLE TB_DESTINATION
    MODIFY COLUMN DEST_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '플레이스 내부 식별자',
    MODIFY COLUMN DEST_NAME VARCHAR(100) NOT NULL COMMENT '플레이스명',
    MODIFY COLUMN DEST_DESC LONGTEXT NULL COMMENT '플레이스의 상세 소개와 설명',
    MODIFY COLUMN COUNTRY_ID BIGINT NOT NULL COMMENT '플레이스가 속한 국가 식별자이며 TB_COUNTRY 참조',
    MODIFY COLUMN REGION_ID BIGINT NOT NULL COMMENT '플레이스가 속한 지역 식별자이며 TB_REGION 참조',
    MODIFY COLUMN CATEGORY VARCHAR(30) NOT NULL COMMENT '플레이스 구분 코드로 FOOD, SIGHTSEEING, SHOPPING, ACCOMMODATION, CAFE, NATURE, CULTURE, ACTIVITY',
    MODIFY COLUMN IMAGE_URL VARCHAR(500) NULL COMMENT '플레이스 대표 이미지 URL',
    MODIFY COLUMN MAP_LAT DOUBLE NOT NULL COMMENT '지도 표시용 위도',
    MODIFY COLUMN MAP_LNG DOUBLE NOT NULL COMMENT '지도 표시용 경도',
    MODIFY COLUMN LIKE_COUNT INT NOT NULL DEFAULT 0 COMMENT '플레이스 좋아요 누적 수',
    MODIFY COLUMN CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '플레이스 등록 일시';

ALTER TABLE TB_TRAVEL_PLAN COMMENT = '회원이 작성한 여행 계획의 제목, 기간, 공개 상태와 집계 정보를 저장하는 테이블';
ALTER TABLE TB_TRAVEL_PLAN
    MODIFY COLUMN PLAN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '여행 계획 내부 식별자',
    MODIFY COLUMN USER_ID BIGINT NULL COMMENT '계획 작성 회원 식별자이며 탈퇴 회원 계획은 NULL 가능',
    MODIFY COLUMN USER_NICKNM VARCHAR(50) NOT NULL COMMENT '계획 작성 시점의 작성자 닉네임',
    MODIFY COLUMN TITLE VARCHAR(150) NOT NULL COMMENT '여행 계획 제목',
    MODIFY COLUMN DESCRIPTION VARCHAR(500) NULL COMMENT '여행 계획 요약 설명',
    MODIFY COLUMN IMAGE_URL VARCHAR(500) NULL COMMENT '여행 계획 대표 이미지 URL',
    MODIFY COLUMN TRAVEL_START_DT DATE NULL COMMENT '여행 시작일',
    MODIFY COLUMN TRAVEL_END_DT DATE NULL COMMENT '여행 종료일',
    MODIFY COLUMN SPOT_COUNT INT NOT NULL DEFAULT 0 COMMENT '계획에 포함된 플레이스 또는 일정 지점 수',
    MODIFY COLUMN LIKE_COUNT INT NOT NULL DEFAULT 0 COMMENT '여행 계획 좋아요 누적 수',
    MODIFY COLUMN VIEW_COUNT BIGINT NOT NULL DEFAULT 0 COMMENT '여행 계획 조회 누적 수',
    MODIFY COLUMN IS_PUBLIC CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '공개 여부로 Y는 공개, N은 비공개',
    MODIFY COLUMN CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '여행 계획 등록 일시',
    MODIFY COLUMN MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '여행 계획 최종 수정 일시';

ALTER TABLE TB_TRAVEL_DAY COMMENT = '여행 계획을 날짜와 일차 단위로 분리해 관리하는 테이블';
ALTER TABLE TB_TRAVEL_DAY
    MODIFY COLUMN DAY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '여행 일차 내부 식별자',
    MODIFY COLUMN PLAN_ID BIGINT NOT NULL COMMENT '소속 여행 계획 식별자이며 TB_TRAVEL_PLAN 참조',
    MODIFY COLUMN DAY_NO INT NOT NULL COMMENT '여행 계획 내 일차 번호',
    MODIFY COLUMN PLAN_DATE DATE NOT NULL COMMENT '해당 일차의 실제 여행 날짜';

ALTER TABLE TB_TRAVEL_DAY_REGION COMMENT = '여행 일차별 방문 국가와 지역 및 지역 단위 메모를 연결하는 테이블';
ALTER TABLE TB_TRAVEL_DAY_REGION
    MODIFY COLUMN DAY_REGION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '일차별 방문 지역 내부 식별자',
    MODIFY COLUMN DAY_ID BIGINT NOT NULL COMMENT '소속 여행 일차 식별자이며 TB_TRAVEL_DAY 참조',
    MODIFY COLUMN COUNTRY_ID BIGINT NOT NULL COMMENT '방문 국가 식별자이며 TB_COUNTRY 참조',
    MODIFY COLUMN REGION_ID BIGINT NOT NULL COMMENT '방문 지역 식별자이며 TB_REGION 참조',
    MODIFY COLUMN REGION_NOTE VARCHAR(500) NULL COMMENT '해당 지역의 숙소나 이동 관련 메모',
    MODIFY COLUMN SORT_ORDER INT NOT NULL COMMENT '같은 일차 안에서 지역의 방문 순서';

ALTER TABLE TB_TRAVEL_SCHEDULE COMMENT = '여행 일차의 지역별 세부 일정과 장소, 시간을 저장하는 테이블';
ALTER TABLE TB_TRAVEL_SCHEDULE
    MODIFY COLUMN SCHEDULE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '세부 일정 내부 식별자',
    MODIFY COLUMN DAY_REGION_ID BIGINT NOT NULL COMMENT '소속 일차별 방문 지역 식별자이며 TB_TRAVEL_DAY_REGION 참조',
    MODIFY COLUMN SCHEDULE_TIME VARCHAR(5) NULL COMMENT '일정 시작 시각을 HH:mm 형식으로 저장',
    MODIFY COLUMN TITLE VARCHAR(150) NULL COMMENT '세부 일정 제목',
    MODIFY COLUMN LOCATION VARCHAR(150) NULL COMMENT '세부 일정 장소명',
    MODIFY COLUMN MEMO VARCHAR(500) NULL COMMENT '예약 정보나 주의사항 등 일정 메모',
    MODIFY COLUMN SORT_ORDER INT NOT NULL COMMENT '같은 지역 안에서 세부 일정 노출 순서';

ALTER TABLE TB_TRAVEL_TRANSPORT COMMENT = '세부 일정에 연결된 이동수단과 출발·도착 정보를 저장하는 테이블';
ALTER TABLE TB_TRAVEL_TRANSPORT
    MODIFY COLUMN TRANSPORT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '이동정보 내부 식별자',
    MODIFY COLUMN SCHEDULE_ID BIGINT NOT NULL COMMENT '연결된 세부 일정 식별자이며 일정당 하나만 등록',
    MODIFY COLUMN TRANSPORT_TYPE VARCHAR(20) NOT NULL COMMENT '이동수단 코드로 TRAIN, CAR, FLIGHT, CRUISE, OTHER',
    MODIFY COLUMN TRANSPORT_NAME VARCHAR(100) NULL COMMENT '항공편, 열차편, 차량 등 이동수단 명칭',
    MODIFY COLUMN DEPARTURE_TIME VARCHAR(5) NULL COMMENT '출발 시각을 HH:mm 형식으로 저장',
    MODIFY COLUMN ARRIVAL_TIME VARCHAR(5) NULL COMMENT '도착 시각을 HH:mm 형식으로 저장',
    MODIFY COLUMN TRANSPORT_MEMO VARCHAR(500) NULL COMMENT '좌석, 터미널, 승강장 등 이동 관련 메모';

ALTER TABLE TB_TRAVEL_PACKING_ITEM COMMENT = '여행 계획별 준비물과 필수 여부를 관리하는 테이블';
ALTER TABLE TB_TRAVEL_PACKING_ITEM
    MODIFY COLUMN PACKING_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '준비물 내부 식별자',
    MODIFY COLUMN PLAN_ID BIGINT NOT NULL COMMENT '소속 여행 계획 식별자이며 TB_TRAVEL_PLAN 참조',
    MODIFY COLUMN ITEM_NAME VARCHAR(100) NOT NULL COMMENT '준비물 이름',
    MODIFY COLUMN REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '필수 준비물 여부로 Y는 필수, N은 선택',
    MODIFY COLUMN SORT_ORDER INT NOT NULL COMMENT '여행 계획 내 준비물 노출 순서';

ALTER TABLE TB_ADMIN_DEPT COMMENT = '관리자 역할을 조직 단위로 분류하기 위한 운영 부서 기준 테이블';
ALTER TABLE TB_ADMIN_DEPT
    MODIFY COLUMN DEPT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '관리자 부서 내부 식별자',
    MODIFY COLUMN DEPT_CODE VARCHAR(50) NOT NULL COMMENT '관리자 부서 고유 코드',
    MODIFY COLUMN DEPT_NAME VARCHAR(100) NOT NULL COMMENT '관리자 부서명',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '부서 사용 여부로 Y는 사용, N은 미사용';

ALTER TABLE TB_ADMIN_ROLE COMMENT = '관리자 권한 등급과 소속 부서를 정의하는 역할 기준 테이블';
ALTER TABLE TB_ADMIN_ROLE
    MODIFY COLUMN ROLE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '관리자 역할 내부 식별자',
    MODIFY COLUMN ROLE_CODE VARCHAR(50) NOT NULL COMMENT 'ADMIN, MASTER, SENIOR, JUNIOR 등의 고유 역할 코드',
    MODIFY COLUMN ROLE_NAME VARCHAR(100) NOT NULL COMMENT '화면에 표시하는 관리자 역할명',
    MODIFY COLUMN ROLE_LEVEL INT NOT NULL COMMENT '권한 비교와 계층 판단에 사용하는 역할 수준 값',
    MODIFY COLUMN DEPT_ID BIGINT NULL COMMENT '역할이 속한 관리자 부서 식별자이며 TB_ADMIN_DEPT 참조',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '역할 사용 여부로 Y는 사용, N은 미사용';

ALTER TABLE TB_ADMIN_PERMISSION COMMENT = '관리자 기능 접근과 작업 권한을 코드 단위로 정의하는 테이블';
ALTER TABLE TB_ADMIN_PERMISSION
    MODIFY COLUMN PERMISSION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '관리자 권한 내부 식별자',
    MODIFY COLUMN PERMISSION_CODE VARCHAR(100) NOT NULL COMMENT '애플리케이션에서 검사하는 고유 권한 코드',
    MODIFY COLUMN PERMISSION_NAME VARCHAR(100) NOT NULL COMMENT '관리자가 이해할 수 있는 권한명',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '권한 사용 여부로 Y는 사용, N은 미사용';

ALTER TABLE TB_ADMIN_MENU COMMENT = '관리자 화면의 메뉴 구조, 경로와 노출 순서를 정의하는 테이블';
ALTER TABLE TB_ADMIN_MENU
    MODIFY COLUMN MENU_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '관리자 메뉴 내부 식별자',
    MODIFY COLUMN MENU_CODE VARCHAR(100) NOT NULL COMMENT '관리자 메뉴 고유 코드',
    MODIFY COLUMN MENU_NAME VARCHAR(100) NOT NULL COMMENT '화면에 표시하는 관리자 메뉴명',
    MODIFY COLUMN PARENT_MENU_ID BIGINT NULL COMMENT '상위 메뉴 식별자이며 최상위 메뉴는 NULL',
    MODIFY COLUMN MENU_PATH VARCHAR(200) NULL COMMENT '프론트엔드 관리자 화면 경로',
    MODIFY COLUMN SORT_ORDER INT NOT NULL DEFAULT 0 COMMENT '같은 단계에서 메뉴가 표시되는 순서',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '메뉴 사용 여부로 Y는 노출 가능, N은 미사용';

ALTER TABLE TB_ADMIN_ROLE_PERMISSION COMMENT = '관리자 역할과 기능 권한의 허용 관계를 관리하는 연결 테이블';
ALTER TABLE TB_ADMIN_ROLE_PERMISSION
    MODIFY COLUMN ROLE_PERMISSION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '역할-권한 연결 내부 식별자',
    MODIFY COLUMN ROLE_ID BIGINT NOT NULL COMMENT '관리자 역할 식별자이며 TB_ADMIN_ROLE 참조',
    MODIFY COLUMN PERMISSION_ID BIGINT NOT NULL COMMENT '관리자 권한 식별자이며 TB_ADMIN_PERMISSION 참조',
    MODIFY COLUMN ALLOW_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '해당 역할의 권한 허용 여부로 Y는 허용, N은 차단';

ALTER TABLE TB_ADMIN_ROLE_MENU COMMENT = '관리자 역할별 접근 가능한 메뉴와 필요 권한을 관리하는 연결 테이블';
ALTER TABLE TB_ADMIN_ROLE_MENU
    MODIFY COLUMN ROLE_MENU_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '역할-메뉴 연결 내부 식별자',
    MODIFY COLUMN ROLE_ID BIGINT NOT NULL COMMENT '관리자 역할 식별자이며 TB_ADMIN_ROLE 참조',
    MODIFY COLUMN MENU_ID BIGINT NOT NULL COMMENT '관리자 메뉴 식별자이며 TB_ADMIN_MENU 참조',
    MODIFY COLUMN PERMISSION_ID BIGINT NULL COMMENT '메뉴 접근에 필요한 권한 식별자이며 TB_ADMIN_PERMISSION 참조',
    MODIFY COLUMN ALLOW_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '해당 역할의 메뉴 접근 허용 여부로 Y는 허용, N은 차단';

ALTER TABLE TB_ADMIN_USER_ROLE COMMENT = '관리자 회원에게 하나 이상의 관리자 역할을 부여하는 연결 테이블';
ALTER TABLE TB_ADMIN_USER_ROLE
    MODIFY COLUMN USER_ROLE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '사용자-역할 연결 내부 식별자',
    MODIFY COLUMN USER_ID BIGINT NOT NULL COMMENT '관리자 회원 식별자이며 TB_USER_MSTR 참조',
    MODIFY COLUMN ROLE_ID BIGINT NOT NULL COMMENT '부여된 관리자 역할 식별자이며 TB_ADMIN_ROLE 참조',
    MODIFY COLUMN PRIMARY_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '여러 역할 중 대표 역할 여부로 Y는 대표 역할';

ALTER TABLE TB_DEST_RECOMMEND COMMENT = '홈 화면 등에 노출할 추천 플레이스와 노출 기간 및 순서를 관리하는 테이블';
ALTER TABLE TB_DEST_RECOMMEND
    MODIFY COLUMN RECOMMEND_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '추천 설정 내부 식별자',
    MODIFY COLUMN DEST_ID BIGINT NOT NULL COMMENT '추천 대상으로 지정한 플레이스 식별자이며 TB_DESTINATION 참조',
    MODIFY COLUMN DISPLAY_START_DT DATETIME(6) NOT NULL COMMENT '추천 노출 시작 일시',
    MODIFY COLUMN DISPLAY_END_DT DATETIME(6) NOT NULL COMMENT '추천 노출 종료 일시',
    MODIFY COLUMN SORT_ORDER INT NOT NULL DEFAULT 1 COMMENT '추천 영역 내 노출 순서',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '추천 설정 사용 여부로 Y는 사용, N은 미사용',
    MODIFY COLUMN IMAGE_URL VARCHAR(500) NULL COMMENT '추천 영역에서 별도로 사용할 대표 이미지 URL';

ALTER TABLE TB_TRAVEL_PRODUCT COMMENT = '플레이스에 연결된 입장권, 투어, 패스 등 예약 가능한 여행 상품 테이블';
ALTER TABLE TB_TRAVEL_PRODUCT
    MODIFY COLUMN PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '여행 상품 내부 식별자',
    MODIFY COLUMN DEST_ID BIGINT NOT NULL COMMENT '상품이 연결된 플레이스 식별자이며 TB_DESTINATION 참조',
    MODIFY COLUMN PRODUCT_NAME VARCHAR(150) NOT NULL COMMENT '고객에게 표시하는 여행 상품명',
    MODIFY COLUMN PRODUCT_SUMMARY VARCHAR(300) NULL COMMENT '상품 목록과 카드에 표시하는 한 줄 요약',
    MODIFY COLUMN PRODUCT_TYPE VARCHAR(30) NOT NULL COMMENT '상품 유형 코드로 TICKET, TOUR, PASS, ACTIVITY, TRANSPORT, ETC',
    MODIFY COLUMN PROVIDER_NAME VARCHAR(100) NULL COMMENT '상품을 판매하거나 제공하는 업체명',
    MODIFY COLUMN PRODUCT_DESC LONGTEXT NULL COMMENT '상품의 전체 상세 설명',
    MODIFY COLUMN IMAGE_URL VARCHAR(500) NULL COMMENT '상품 대표 이미지 URL',
    MODIFY COLUMN DETAIL_IMAGE_URL VARCHAR(500) NULL COMMENT '상품 상세 설명에 표시하는 이미지 URL',
    MODIFY COLUMN BOOKING_URL VARCHAR(1000) NULL COMMENT '외부 판매처 또는 예약 페이지 URL',
    MODIFY COLUMN PRICE DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '상품 기본 판매 가격',
    MODIFY COLUMN CURRENCY VARCHAR(3) NOT NULL DEFAULT 'KRW' COMMENT 'ISO 4217 형식의 통화 코드',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '상품 판매 및 노출 여부로 Y는 사용, N은 미사용',
    MODIFY COLUMN SORT_ORDER INT NOT NULL DEFAULT 1 COMMENT '같은 플레이스 내 상품 노출 순서',
    MODIFY COLUMN CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '여행 상품 등록 일시',
    MODIFY COLUMN COURSE_TEXT LONGTEXT NULL COMMENT '투어 이동 경로와 시간대별 코스 설명',
    MODIFY COLUMN INCLUDED_TEXT LONGTEXT NULL COMMENT '상품 가격에 포함되는 서비스와 혜택',
    MODIFY COLUMN EXCLUDED_TEXT LONGTEXT NULL COMMENT '상품 가격에 포함되지 않는 항목',
    MODIFY COLUMN USAGE_GUIDE_TEXT LONGTEXT NULL COMMENT '예약 후 상품을 사용하는 방법과 절차',
    MODIFY COLUMN NOTICE_TEXT LONGTEXT NULL COMMENT '예약과 이용 전에 확인할 주의사항',
    MODIFY COLUMN CANCELLATION_POLICY_TEXT LONGTEXT NULL COMMENT '상품 취소 및 환불 규정',
    MODIFY COLUMN FAQ_TEXT LONGTEXT NULL COMMENT '상품 관련 자주 묻는 질문과 답변',
    MODIFY COLUMN MEETING_TIME VARCHAR(100) NULL COMMENT '투어 또는 액티비티 집합 시간 안내',
    MODIFY COLUMN MEETING_PLACE VARCHAR(300) NULL COMMENT '투어 또는 액티비티 미팅 장소 안내';

ALTER TABLE TB_TRAVEL_PRODUCT_OPTION COMMENT = '여행 상품의 가격, 유효기간, 확정 방식이 다른 판매 옵션을 관리하는 테이블';
ALTER TABLE TB_TRAVEL_PRODUCT_OPTION
    MODIFY COLUMN OPTION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품 옵션 내부 식별자',
    MODIFY COLUMN PRODUCT_ID BIGINT NOT NULL COMMENT '소속 여행 상품 식별자이며 TB_TRAVEL_PRODUCT 참조',
    MODIFY COLUMN OPTION_NAME VARCHAR(150) NOT NULL COMMENT '고객에게 표시하는 상품 옵션명',
    MODIFY COLUMN OPTION_DESC VARCHAR(500) NULL COMMENT '상품 옵션의 구성과 차이를 설명하는 문구',
    MODIFY COLUMN PRICE DECIMAL(12, 2) NOT NULL DEFAULT 0.00 COMMENT '해당 옵션의 판매 가격',
    MODIFY COLUMN CURRENCY VARCHAR(3) NOT NULL DEFAULT 'KRW' COMMENT 'ISO 4217 형식의 옵션 가격 통화 코드',
    MODIFY COLUMN CANCELLATION_POLICY VARCHAR(500) NULL COMMENT '해당 옵션에 적용되는 취소 및 환불 정책',
    MODIFY COLUMN VALIDITY_TEXT VARCHAR(200) NULL COMMENT '옵션의 사용 가능 기간 또는 유효 조건',
    MODIFY COLUMN CONFIRMATION_TYPE VARCHAR(20) NOT NULL DEFAULT 'INSTANT' COMMENT '예약 확정 방식으로 INSTANT 등 확정 유형을 저장',
    MODIFY COLUMN USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '옵션 판매 및 노출 여부로 Y는 사용, N은 미사용',
    MODIFY COLUMN SORT_ORDER INT NOT NULL DEFAULT 1 COMMENT '같은 상품 내 옵션 노출 순서';

