CREATE TABLE TB_USER_MSTR (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_EMAIL VARCHAR(100) NOT NULL,
    USER_PWD VARCHAR(255),
    USER_NICKNM VARCHAR(50) NOT NULL,
    SNS_PROVIDER VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    SNS_PROVIDER_ID VARCHAR(100),
    USER_ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    USER_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    USER_PHONE VARCHAR(20),
    USER_ZIPCODE VARCHAR(10),
    USER_ADDR VARCHAR(200),
    USER_ADDR_DETAIL VARCHAR(200),
    USER_BIRTH VARCHAR(10),
    JOIN_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USER_EMAIL UNIQUE (USER_EMAIL),
    CONSTRAINT UK_USER_NICK UNIQUE (USER_NICKNM),
    CONSTRAINT CK_USER_DEL CHECK (DEL_YN IN ('Y', 'N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_COUNTRY (
    COUNTRY_ID BIGINT NOT NULL AUTO_INCREMENT,
    COUNTRY_NAME VARCHAR(50) NOT NULL,
    COUNTRY_CODE VARCHAR(10) NOT NULL,
    COUNTRY_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT UK_COUNTRY_NAME UNIQUE (COUNTRY_NAME),
    CONSTRAINT UK_COUNTRY_CODE UNIQUE (COUNTRY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_REGION (
    REGION_ID BIGINT NOT NULL AUTO_INCREMENT,
    COUNTRY_ID BIGINT NOT NULL,
    REGION_NAME VARCHAR(50) NOT NULL,
    REGION_CODE VARCHAR(20) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    REGION_STAT_CD VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_REGION PRIMARY KEY (REGION_ID),
    CONSTRAINT UK_REGION_CODE UNIQUE (COUNTRY_ID, REGION_CODE),
    CONSTRAINT FK_REGION_CTRY FOREIGN KEY (COUNTRY_ID) REFERENCES TB_COUNTRY (COUNTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_DESTINATION (
    DEST_ID BIGINT NOT NULL AUTO_INCREMENT,
    DEST_NAME VARCHAR(100) NOT NULL,
    DEST_DESC LONGTEXT,
    COUNTRY_ID BIGINT NOT NULL,
    REGION_ID BIGINT NOT NULL,
    CATEGORY VARCHAR(30) NOT NULL,
    IMAGE_URL VARCHAR(500),
    MAP_LAT DOUBLE NOT NULL,
    MAP_LNG DOUBLE NOT NULL,
    LIKE_COUNT INT NOT NULL DEFAULT 0,
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_DESTINATION PRIMARY KEY (DEST_ID),
    CONSTRAINT FK_DEST_CTRY FOREIGN KEY (COUNTRY_ID) REFERENCES TB_COUNTRY (COUNTRY_ID),
    CONSTRAINT FK_DEST_REGION FOREIGN KEY (REGION_ID) REFERENCES TB_REGION (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_PLAN (
    PLAN_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT,
    USER_NICKNM VARCHAR(50) NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(500),
    IMAGE_URL VARCHAR(500),
    TRAVEL_START_DT DATE,
    TRAVEL_END_DT DATE,
    SPOT_COUNT INT NOT NULL DEFAULT 0,
    LIKE_COUNT INT NOT NULL DEFAULT 0,
    IS_PUBLIC CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_TRAVEL_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_PLAN_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER_MSTR (USER_ID) ON DELETE SET NULL,
    CONSTRAINT CK_PLAN_PUBLIC CHECK (IS_PUBLIC IN ('Y', 'N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_DAY (
    DAY_ID BIGINT NOT NULL AUTO_INCREMENT,
    PLAN_ID BIGINT NOT NULL,
    DAY_NO INT NOT NULL,
    PLAN_DATE DATE NOT NULL,
    CONSTRAINT PK_TRAVEL_DAY PRIMARY KEY (DAY_ID),
    CONSTRAINT UK_TRAVEL_DAY_PLAN_DAY UNIQUE (PLAN_ID, DAY_NO),
    CONSTRAINT FK_DAY_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TB_TRAVEL_PLAN (PLAN_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_DAY_REGION (
    DAY_REGION_ID BIGINT NOT NULL AUTO_INCREMENT,
    DAY_ID BIGINT NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    REGION_ID BIGINT NOT NULL,
    REGION_NOTE VARCHAR(500),
    SORT_ORDER INT NOT NULL,
    CONSTRAINT PK_TRAVEL_DAY_REG PRIMARY KEY (DAY_REGION_ID),
    CONSTRAINT FK_DAY_REG_DAY FOREIGN KEY (DAY_ID) REFERENCES TB_TRAVEL_DAY (DAY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DAY_REG_CTRY FOREIGN KEY (COUNTRY_ID) REFERENCES TB_COUNTRY (COUNTRY_ID),
    CONSTRAINT FK_DAY_REG_REGION FOREIGN KEY (REGION_ID) REFERENCES TB_REGION (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_SCHEDULE (
    SCHEDULE_ID BIGINT NOT NULL AUTO_INCREMENT,
    DAY_REGION_ID BIGINT NOT NULL,
    SCHEDULE_TIME VARCHAR(5),
    TITLE VARCHAR(150),
    LOCATION VARCHAR(150),
    MEMO VARCHAR(500),
    SORT_ORDER INT NOT NULL,
    CONSTRAINT PK_TRAVEL_SCHEDULE PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT FK_SCHED_DAY_REG FOREIGN KEY (DAY_REGION_ID) REFERENCES TB_TRAVEL_DAY_REGION (DAY_REGION_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_TRANSPORT (
    TRANSPORT_ID BIGINT NOT NULL AUTO_INCREMENT,
    SCHEDULE_ID BIGINT NOT NULL,
    TRANSPORT_TYPE VARCHAR(20) NOT NULL,
    TRANSPORT_NAME VARCHAR(100),
    DEPARTURE_TIME VARCHAR(5),
    ARRIVAL_TIME VARCHAR(5),
    TRANSPORT_MEMO VARCHAR(500),
    CONSTRAINT PK_TRAVEL_TRANSPORT PRIMARY KEY (TRANSPORT_ID),
    CONSTRAINT UK_TRANSPORT_SCHED UNIQUE (SCHEDULE_ID),
    CONSTRAINT FK_TRANS_SCHED FOREIGN KEY (SCHEDULE_ID) REFERENCES TB_TRAVEL_SCHEDULE (SCHEDULE_ID) ON DELETE CASCADE,
    CONSTRAINT CK_TRANS_TYPE CHECK (TRANSPORT_TYPE IN ('TRAIN', 'CAR', 'FLIGHT', 'CRUISE', 'OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_TRAVEL_PACKING_ITEM (
    PACKING_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    PLAN_ID BIGINT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'Y',
    SORT_ORDER INT NOT NULL,
    CONSTRAINT PK_TRAVEL_PACKING PRIMARY KEY (PACKING_ITEM_ID),
    CONSTRAINT FK_PACKING_PLAN FOREIGN KEY (PLAN_ID) REFERENCES TB_TRAVEL_PLAN (PLAN_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PACKING_REQ CHECK (REQUIRED_YN IN ('Y', 'N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_USER_SNS ON TB_USER_MSTR (SNS_PROVIDER, SNS_PROVIDER_ID);
CREATE INDEX IX_REGION_CTRY_SORT ON TB_REGION (COUNTRY_ID, SORT_ORDER, REGION_NAME);
CREATE INDEX IX_DEST_LIKE ON TB_DESTINATION (LIKE_COUNT DESC);
CREATE INDEX IX_DEST_CTRY ON TB_DESTINATION (COUNTRY_ID);
CREATE INDEX IX_DEST_REGION ON TB_DESTINATION (REGION_ID);
CREATE INDEX IX_PLAN_USER_MDFY ON TB_TRAVEL_PLAN (USER_ID, MDFY_DT DESC);
CREATE INDEX IX_PLAN_PUBLIC_LIKE ON TB_TRAVEL_PLAN (IS_PUBLIC, LIKE_COUNT DESC);
CREATE INDEX IX_DAY_PLAN_DATE ON TB_TRAVEL_DAY (PLAN_ID, PLAN_DATE);
CREATE INDEX IX_DAY_REG_DAY_SORT ON TB_TRAVEL_DAY_REGION (DAY_ID, SORT_ORDER);
CREATE INDEX IX_SCHED_REG_SORT ON TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SORT_ORDER);
CREATE INDEX IX_PACK_PLAN_SORT ON TB_TRAVEL_PACKING_ITEM (PLAN_ID, SORT_ORDER);
