CREATE TABLE TB_PRODUCT_ORDER (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '상품 주문 내부 식별자',
    ORDER_NO VARCHAR(40) NOT NULL COMMENT '고객에게 안내하는 고유 주문번호',
    USER_ID BIGINT NOT NULL COMMENT '주문한 회원 식별자이며 TB_USER_MSTR 참조',
    PRODUCT_ID BIGINT NULL COMMENT '주문 대상 여행 상품 식별자이며 삭제된 상품은 NULL',
    OPTION_ID BIGINT NULL COMMENT '주문 대상 상품 옵션 식별자이며 삭제된 옵션은 NULL',
    PRODUCT_NAME VARCHAR(150) NOT NULL COMMENT '주문 시점의 상품명 스냅샷',
    OPTION_NAME VARCHAR(150) NOT NULL COMMENT '주문 시점의 옵션명 스냅샷',
    PRODUCT_IMAGE_URL VARCHAR(500) NULL COMMENT '주문 시점의 상품 대표 이미지 URL',
    DESTINATION_NAME VARCHAR(150) NOT NULL COMMENT '주문 시점의 국가, 지역, 플레이스명',
    QUANTITY INT NOT NULL COMMENT '구매 수량',
    UNIT_PRICE DECIMAL(12, 2) NOT NULL COMMENT '주문 시점의 옵션 단가',
    TOTAL_PRICE DECIMAL(12, 2) NOT NULL COMMENT '옵션 단가와 수량을 곱한 주문 총액',
    CURRENCY VARCHAR(3) NOT NULL COMMENT 'ISO 4217 형식의 주문 통화 코드',
    USE_DATE DATE NOT NULL COMMENT '고객이 선택한 상품 이용 예정일',
    BUYER_NAME VARCHAR(50) NOT NULL COMMENT '상품을 이용하거나 예약하는 구매자명',
    BUYER_EMAIL VARCHAR(100) NOT NULL COMMENT '바우처와 예약 안내를 받을 이메일',
    BUYER_PHONE VARCHAR(20) NULL COMMENT '예약 안내를 받을 연락처',
    ORDER_STATUS VARCHAR(20) NOT NULL DEFAULT 'ORDERED' COMMENT '주문 상태로 ORDERED, CONFIRMED, CANCELLED 등을 저장',
    PAYMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '결제 상태로 PENDING, PAID, FAILED, REFUNDED 등을 저장',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '주문 접수 일시',
    CONSTRAINT PK_PRODUCT_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT UK_PRODUCT_ORDER_NO UNIQUE (ORDER_NO),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER_MSTR (USER_ID),
    CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_TRAVEL_PRODUCT (PRODUCT_ID) ON DELETE SET NULL,
    CONSTRAINT FK_ORDER_OPTION FOREIGN KEY (OPTION_ID) REFERENCES TB_TRAVEL_PRODUCT_OPTION (OPTION_ID) ON DELETE SET NULL,
    CONSTRAINT CK_ORDER_QUANTITY CHECK (QUANTITY BETWEEN 1 AND 10),
    CONSTRAINT CK_ORDER_UNIT_PRICE CHECK (UNIT_PRICE >= 0),
    CONSTRAINT CK_ORDER_TOTAL_PRICE CHECK (TOTAL_PRICE >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='회원이 홈페이지에서 옵션상품을 선택해 접수한 주문과 결제 상태를 보존하는 테이블';

CREATE INDEX IX_PRODUCT_ORDER_USER_DT ON TB_PRODUCT_ORDER (USER_ID, CREATE_DT);
