-- Public product catalogue: WHERE USE_YN = ? ORDER BY SORT_ORDER, CREATE_DT DESC
CREATE INDEX IX_PRODUCT_USE_SORT_DT
    ON TB_TRAVEL_PRODUCT (USE_YN, SORT_ORDER, CREATE_DT DESC);

-- Product option lookup: WHERE PRODUCT_ID = ? AND USE_YN = ? ORDER BY SORT_ORDER, OPTION_ID
CREATE INDEX IX_PRODUCT_OPTION_USE_SORT
    ON TB_TRAVEL_PRODUCT_OPTION (PRODUCT_ID, USE_YN, SORT_ORDER, OPTION_ID);

-- Admin member/staff filters and latest-join ordering.
CREATE INDEX IX_USER_ADMIN_FILTER
    ON TB_USER_MSTR (DEL_YN, USER_ROLE, USER_STAT_CD, JOIN_DT DESC, USER_ID DESC);

-- Admin destination list: ORDER BY DEST_NAME.
CREATE INDEX IX_DEST_NAME
    ON TB_DESTINATION (DEST_NAME);

-- The existing index also supports FK_ORDER_USER, so recreate that foreign key
-- while extending the index for deterministic order-history sorting. MySQL must
-- perform the drop and re-add in separate statements when the name is unchanged.
ALTER TABLE TB_PRODUCT_ORDER DROP FOREIGN KEY FK_ORDER_USER;
DROP INDEX IX_PRODUCT_ORDER_USER_DT ON TB_PRODUCT_ORDER;
CREATE INDEX IX_PRODUCT_ORDER_USER_DT
    ON TB_PRODUCT_ORDER (USER_ID, CREATE_DT DESC, ORDER_ID DESC);
ALTER TABLE TB_PRODUCT_ORDER
    ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID)
        REFERENCES TB_USER_MSTR (USER_ID);

-- Order operation dashboards and payment/status filters.
CREATE INDEX IX_PRODUCT_ORDER_STATUS_DT
    ON TB_PRODUCT_ORDER (PAYMENT_STATUS, ORDER_STATUS, CREATE_DT DESC);

-- Upcoming product usage and reservation-operation queries.
CREATE INDEX IX_PRODUCT_ORDER_USE_DT
    ON TB_PRODUCT_ORDER (USE_DATE, ORDER_STATUS);
