CREATE TABLE TB_PARTNER_COMPANY (
    PARTNER_ID BIGINT NOT NULL AUTO_INCREMENT,
    PARTNER_CODE VARCHAR(30) NOT NULL,
    PARTNER_NAME VARCHAR(120) NOT NULL,
    BUSINESS_NUMBER VARCHAR(30),
    REPRESENTATIVE_NAME VARCHAR(50),
    MANAGER_NAME VARCHAR(50),
    MANAGER_EMAIL VARCHAR(100),
    MANAGER_PHONE VARCHAR(30),
    WEBSITE_URL VARCHAR(500),
    COMMISSION_RATE DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    PARTNER_STATUS VARCHAR(20) NOT NULL DEFAULT 'ONBOARDING',
    MEMO VARCHAR(1000),
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_PARTNER_COMPANY PRIMARY KEY (PARTNER_ID),
    CONSTRAINT UK_PARTNER_CODE UNIQUE (PARTNER_CODE),
    CONSTRAINT UK_PARTNER_BUSINESS_NO UNIQUE (BUSINESS_NUMBER),
    CONSTRAINT CK_PARTNER_COMMISSION CHECK (COMMISSION_RATE BETWEEN 0 AND 100),
    CONSTRAINT CK_PARTNER_STATUS CHECK (PARTNER_STATUS IN ('ONBOARDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE TB_TRAVEL_PRODUCT
    ADD COLUMN PARTNER_ID BIGINT NULL AFTER DEST_ID,
    ADD COLUMN REGISTRATION_SOURCE VARCHAR(20) NOT NULL DEFAULT 'ADMIN' AFTER PROVIDER_NAME,
    ADD COLUMN APPROVAL_STATUS VARCHAR(20) NOT NULL DEFAULT 'APPROVED' AFTER REGISTRATION_SOURCE,
    ADD COLUMN APPROVAL_MEMO VARCHAR(500) NULL AFTER APPROVAL_STATUS,
    ADD COLUMN SUBMIT_DT DATETIME(6) NULL AFTER APPROVAL_MEMO,
    ADD COLUMN APPROVE_DT DATETIME(6) NULL AFTER SUBMIT_DT,
    ADD CONSTRAINT FK_PRODUCT_PARTNER FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER_COMPANY (PARTNER_ID),
    ADD CONSTRAINT CK_PRODUCT_SOURCE CHECK (REGISTRATION_SOURCE IN ('ADMIN', 'PARTNER')),
    ADD CONSTRAINT CK_PRODUCT_APPROVAL CHECK (APPROVAL_STATUS IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED'));

INSERT INTO TB_PARTNER_COMPANY (
    PARTNER_CODE, PARTNER_NAME, PARTNER_STATUS, COMMISSION_RATE, MEMO
)
SELECT CONCAT('LEGACY-', LPAD(source.RN, 3, '0')),
       source.PROVIDER_NAME,
       'ACTIVE',
       12.00,
       '기존 상품 판매처에서 자동 전환된 파트너사'
FROM (
    SELECT PROVIDER_NAME, ROW_NUMBER() OVER (ORDER BY PROVIDER_NAME) AS RN
    FROM (SELECT DISTINCT PROVIDER_NAME FROM TB_TRAVEL_PRODUCT WHERE PROVIDER_NAME IS NOT NULL) providers
) source
WHERE NOT EXISTS (
    SELECT 1 FROM TB_PARTNER_COMPANY partner WHERE partner.PARTNER_NAME = source.PROVIDER_NAME
);

UPDATE TB_TRAVEL_PRODUCT product
JOIN TB_PARTNER_COMPANY partner ON partner.PARTNER_NAME = product.PROVIDER_NAME
SET product.PARTNER_ID = partner.PARTNER_ID,
    product.APPROVAL_STATUS = 'APPROVED',
    product.APPROVE_DT = product.CREATE_DT
WHERE product.PARTNER_ID IS NULL;

CREATE INDEX IX_PARTNER_STATUS_NAME ON TB_PARTNER_COMPANY (PARTNER_STATUS, PARTNER_NAME);
CREATE INDEX IX_PRODUCT_PARTNER_APPROVAL ON TB_TRAVEL_PRODUCT (PARTNER_ID, APPROVAL_STATUS, USE_YN, SORT_ORDER);

INSERT INTO TB_ADMIN_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, USE_YN)
SELECT 'PARTNER_MANAGE', '파트너사 관리', 'Y'
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_PERMISSION WHERE PERMISSION_CODE = 'PARTNER_MANAGE');

INSERT INTO TB_ADMIN_MENU (MENU_CODE, MENU_NAME, MENU_PATH, SORT_ORDER, USE_YN)
SELECT 'PARTNERS', '파트너사 관리', '/admin/partners', 35, 'Y'
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_MENU WHERE MENU_CODE = 'PARTNERS');

INSERT INTO TB_ADMIN_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, ALLOW_YN)
SELECT r.ROLE_ID, p.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE r
JOIN TB_ADMIN_PERMISSION p ON p.PERMISSION_CODE = 'PARTNER_MANAGE'
WHERE r.ROLE_CODE IN ('ADMIN', 'MASTER')
  AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_PERMISSION mapping WHERE mapping.ROLE_ID = r.ROLE_ID AND mapping.PERMISSION_ID = p.PERMISSION_ID);

INSERT INTO TB_ADMIN_ROLE_MENU (ROLE_ID, MENU_ID, PERMISSION_ID, ALLOW_YN)
SELECT r.ROLE_ID, m.MENU_ID, p.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE r
JOIN TB_ADMIN_MENU m ON m.MENU_CODE = 'PARTNERS'
JOIN TB_ADMIN_PERMISSION p ON p.PERMISSION_CODE = 'PARTNER_MANAGE'
WHERE r.ROLE_CODE IN ('ADMIN', 'MASTER')
  AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_MENU mapping WHERE mapping.ROLE_ID = r.ROLE_ID AND mapping.MENU_ID = m.MENU_ID);
