CREATE TABLE TB_PARTNER_USER (
    PARTNER_USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    PARTNER_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PARTNER_ROLE VARCHAR(20) NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MDFY_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_PARTNER_USER PRIMARY KEY (PARTNER_USER_ID),
    CONSTRAINT UK_PARTNER_USER_USER UNIQUE (USER_ID),
    CONSTRAINT UK_PARTNER_USER_MAPPING UNIQUE (PARTNER_ID, USER_ID),
    CONSTRAINT FK_PARTNER_USER_PARTNER FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER_COMPANY (PARTNER_ID),
    CONSTRAINT FK_PARTNER_USER_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER_MSTR (USER_ID),
    CONSTRAINT CK_PARTNER_USER_ROLE CHECK (PARTNER_ROLE IN ('OWNER', 'STAFF')),
    CONSTRAINT CK_PARTNER_USER_USE CHECK (USE_YN IN ('Y', 'N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_PARTNER_USER_PARTNER_ROLE ON TB_PARTNER_USER (PARTNER_ID, PARTNER_ROLE, USE_YN);
