INSERT INTO TB_USER_MSTR (USER_EMAIL, USER_PWD, USER_NICKNM, SNS_PROVIDER, USER_ROLE, USER_STAT_CD, DEL_YN)
SELECT CONCAT('owner', LPAD(SUBSTRING(PARTNER_CODE, -2), 2, '0'), '@demo.routemate.kr'),
       '$2a$10$82pOBoK4r8Uu0Amhql/B7uf3fO4MMqVzYX2264MadS.qMYNMmQrJy',
       CONCAT(PARTNER_NAME, ' 대표'),
       'LOCAL', 'PARTNER_OWNER', 'ACTIVE', 'N'
FROM TB_PARTNER_COMPANY
WHERE PARTNER_CODE LIKE 'DEMO-%'
ON DUPLICATE KEY UPDATE USER_PWD = VALUES(USER_PWD), USER_ROLE = 'PARTNER_OWNER', USER_STAT_CD = 'ACTIVE', DEL_YN = 'N';

INSERT INTO TB_PARTNER_USER (PARTNER_ID, USER_ID, PARTNER_ROLE, USE_YN)
SELECT partner.PARTNER_ID, user.USER_ID, 'OWNER', 'Y'
FROM TB_PARTNER_COMPANY partner
JOIN TB_USER_MSTR user ON user.USER_EMAIL = CONCAT('owner', LPAD(SUBSTRING(partner.PARTNER_CODE, -2), 2, '0'), '@demo.routemate.kr')
WHERE partner.PARTNER_CODE LIKE 'DEMO-%'
ON DUPLICATE KEY UPDATE PARTNER_ROLE = 'OWNER', USE_YN = 'Y';
