ALTER TABLE TB_TRAVEL_PRODUCT DROP CHECK CK_PRODUCT_APPROVAL;
ALTER TABLE TB_TRAVEL_PRODUCT
    ADD CONSTRAINT CK_PRODUCT_APPROVAL CHECK (APPROVAL_STATUS IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'HOLD'));

CREATE TABLE TB_PRODUCT_APPROVAL_HISTORY (
    APPROVAL_HISTORY_ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    DECISION_STATUS VARCHAR(20) NOT NULL,
    DECISION_REASON VARCHAR(500) NULL,
    APPROVER_USER_ID BIGINT NOT NULL,
    DECISION_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_PRODUCT_APPROVAL_HISTORY PRIMARY KEY (APPROVAL_HISTORY_ID),
    CONSTRAINT FK_APPROVAL_HISTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_TRAVEL_PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_APPROVAL_HISTORY_USER FOREIGN KEY (APPROVER_USER_ID) REFERENCES TB_USER_MSTR (USER_ID),
    CONSTRAINT CK_APPROVAL_HISTORY_STATUS CHECK (DECISION_STATUS IN ('APPROVED', 'REJECTED', 'HOLD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_PRODUCT_APPROVAL_HISTORY ON TB_PRODUCT_APPROVAL_HISTORY (PRODUCT_ID, DECISION_DT DESC);

INSERT INTO TB_ADMIN_MENU (MENU_CODE, MENU_NAME, MENU_PATH, SORT_ORDER, USE_YN)
SELECT 'PRODUCT_APPROVALS', '상품 승인 관리', '/admin/product-approvals', 36, 'Y'
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_MENU WHERE MENU_CODE = 'PRODUCT_APPROVALS');

INSERT INTO TB_ADMIN_ROLE_MENU (ROLE_ID, MENU_ID, PERMISSION_ID, ALLOW_YN)
SELECT role.ROLE_ID, menu.MENU_ID, permission.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE role
JOIN TB_ADMIN_MENU menu ON menu.MENU_CODE = 'PRODUCT_APPROVALS'
JOIN TB_ADMIN_PERMISSION permission ON permission.PERMISSION_CODE = 'PARTNER_MANAGE'
WHERE role.ROLE_CODE IN ('ADMIN', 'MASTER')
  AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_MENU mapping WHERE mapping.ROLE_ID = role.ROLE_ID AND mapping.MENU_ID = menu.MENU_ID);
