ALTER TABLE TB_TRAVEL_SCHEDULE
    ADD COLUMN PRODUCT_ORDER_ID BIGINT NULL AFTER DAY_REGION_ID,
    ADD CONSTRAINT FK_SCHEDULE_PRODUCT_ORDER
        FOREIGN KEY (PRODUCT_ORDER_ID) REFERENCES TB_PRODUCT_ORDER (ORDER_ID);

CREATE INDEX IX_SCHEDULE_PRODUCT_ORDER ON TB_TRAVEL_SCHEDULE (PRODUCT_ORDER_ID);
