CREATE TABLE TB_PRODUCT_ORDER_ITEM (
    ORDER_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '주문 항목 식별자',
    ORDER_ID BIGINT NOT NULL COMMENT '주문 헤더 식별자',
    OPTION_ID BIGINT NULL COMMENT '구매 옵션 식별자',
    OPTION_NAME VARCHAR(150) NOT NULL COMMENT '주문 시점 옵션명',
    QUANTITY INT NOT NULL COMMENT '옵션별 구매 수량',
    UNIT_PRICE DECIMAL(12, 2) NOT NULL COMMENT '주문 시점 옵션 단가',
    TOTAL_PRICE DECIMAL(12, 2) NOT NULL COMMENT '옵션별 총 금액',
    CURRENCY VARCHAR(3) NOT NULL COMMENT '통화 코드',
    CONSTRAINT PK_PRODUCT_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_PRODUCT_ORDER (ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_OPTION FOREIGN KEY (OPTION_ID) REFERENCES TB_TRAVEL_PRODUCT_OPTION (OPTION_ID) ON DELETE SET NULL,
    CONSTRAINT CK_ORDER_ITEM_QUANTITY CHECK (QUANTITY BETWEEN 1 AND 10),
    CONSTRAINT CK_ORDER_ITEM_UNIT_PRICE CHECK (UNIT_PRICE >= 0),
    CONSTRAINT CK_ORDER_ITEM_TOTAL_PRICE CHECK (TOTAL_PRICE >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='한 옵션상품 주문에 포함된 옵션별 구매 항목';

CREATE INDEX IX_PRODUCT_ORDER_ITEM_ORDER ON TB_PRODUCT_ORDER_ITEM (ORDER_ID);

ALTER TABLE TB_PRODUCT_ORDER DROP CHECK CK_ORDER_QUANTITY;
ALTER TABLE TB_PRODUCT_ORDER ADD CONSTRAINT CK_ORDER_QUANTITY_POSITIVE CHECK (QUANTITY >= 1);
