INSERT INTO TB_COUNTRY (COUNTRY_NAME, COUNTRY_CODE, COUNTRY_STAT_CD) VALUES
('대한민국', 'KR', 'ACTIVE'), ('일본', 'JP', 'ACTIVE'), ('미국', 'US', 'ACTIVE'),
('프랑스', 'FR', 'ACTIVE'), ('이탈리아', 'IT', 'ACTIVE'), ('스페인', 'ES', 'ACTIVE'),
('영국', 'GB', 'ACTIVE'), ('태국', 'TH', 'ACTIVE'), ('베트남', 'VN', 'ACTIVE'),
('호주', 'AU', 'ACTIVE'), ('싱가포르', 'SG', 'ACTIVE'), ('대만', 'TW', 'ACTIVE'),
('중국', 'CN', 'ACTIVE'), ('캐나다', 'CA', 'ACTIVE'), ('독일', 'DE', 'ACTIVE');

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD)
SELECT COUNTRY_ID, '서울', 'SEL', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'KR';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '부산', 'BUS', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'KR';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '제주', 'CJU', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'KR';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '도쿄', 'TYO', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'JP';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '오사카', 'OSA', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'JP';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '교토', 'KYO', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'JP';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '뉴욕', 'NYC', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'US';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '로스앤젤레스', 'LAX', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'US';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '샌프란시스코', 'SFO', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'US';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '파리', 'PAR', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'FR';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '니스', 'NCE', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'FR';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '리옹', 'LYS', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'FR';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '로마', 'ROM', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'IT';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '밀라노', 'MIL', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'IT';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '베네치아', 'VCE', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'IT';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '바르셀로나', 'BCN', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'ES';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '마드리드', 'MAD', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'ES';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '세비야', 'SVQ', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'ES';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '런던', 'LON', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'GB';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '에든버러', 'EDI', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'GB';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '방콕', 'BKK', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'TH';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '푸껫', 'HKT', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'TH';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '치앙마이', 'CNX', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'TH';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '하노이', 'HAN', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'VN';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '호찌민', 'SGN', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'VN';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '다낭', 'DAD', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'VN';

INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '시드니', 'SYD', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'AU';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '멜버른', 'MEL', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'AU';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '브리즈번', 'BNE', 3, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'AU';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '싱가포르', 'SIN', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'SG';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '타이베이', 'TPE', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'TW';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '베이징', 'PEK', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'CN';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '상하이', 'SHA', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'CN';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '밴쿠버', 'YVR', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'CA';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '토론토', 'YYZ', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'CA';
INSERT INTO TB_REGION (COUNTRY_ID, REGION_NAME, REGION_CODE, SORT_ORDER, REGION_STAT_CD) SELECT COUNTRY_ID, '베를린', 'BER', 1, 'ACTIVE' FROM TB_COUNTRY WHERE COUNTRY_CODE = 'DE';
INSERT INTO TB_REGION SELECT NULL, COUNTRY_ID, '뮌헨', 'MUC', 2, 'ACTIVE', CURRENT_TIMESTAMP(6) FROM TB_COUNTRY WHERE COUNTRY_CODE = 'DE';
