CREATE TABLE TB_STORED_IMAGE (
    IMAGE_ID VARCHAR(36) NOT NULL COMMENT '이미지 식별자',
    CATEGORY VARCHAR(30) NOT NULL COMMENT '이미지 용도',
    RELATIVE_PATH VARCHAR(500) NOT NULL COMMENT 'NAS 루트 기준 상대 경로',
    CONTENT_TYPE VARCHAR(50) NOT NULL COMMENT '검증된 이미지 형식',
    FILE_SIZE BIGINT NOT NULL COMMENT '파일 크기 바이트',
    CREATE_DT DATETIME(6) NOT NULL COMMENT '업로드 일시',
    CONSTRAINT PK_STORED_IMAGE PRIMARY KEY (IMAGE_ID),
    CONSTRAINT UK_STORED_IMAGE_PATH UNIQUE (RELATIVE_PATH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='NAS 이미지 파일 저장 위치';
