CREATE TABLE TB_PRODUCT_PAYMENT (
    PAYMENT_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    PAYMENT_KEY VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'READY',
    METHOD VARCHAR(20) NOT NULL DEFAULT 'MOCK',
    CREATE_DT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT PK_PRODUCT_PAYMENT PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT UK_PRODUCT_PAYMENT_ORDER UNIQUE (ORDER_ID),
    CONSTRAINT UK_PRODUCT_PAYMENT_KEY UNIQUE (PAYMENT_KEY),
    CONSTRAINT FK_PRODUCT_PAYMENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TB_PRODUCT_ORDER (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='상품 주문 결제 시도와 상태';
