INSERT INTO TB_TRAVEL_PLAN (USER_NICKNM, TITLE, DESCRIPTION, TRAVEL_START_DT, TRAVEL_END_DT, SPOT_COUNT, LIKE_COUNT, IS_PUBLIC)
VALUES ('RouteMate', '일본 도쿄·교토 2박 3일', '도쿄의 도심과 교토의 전통 풍경을 함께 둘러보는 샘플 일정', '2026-09-10', '2026-09-12', 2, 0, 'Y');
SET @plan_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 1, '2026-09-10'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '도쿄역 근처 숙소', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='JP' AND r.REGION_CODE='TYO'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '09:00', '도쿄 시내 산책', '아사쿠사·도쿄 스카이트리', '센소지와 스미다강을 둘러봅니다.', 1);
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 2, '2026-09-11'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '신칸센 이동', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='JP' AND r.REGION_CODE='KYO'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '10:00', '교토 사찰 투어', '후시미이나리·기요미즈데라', '아침 일찍 출발합니다.', 1);

INSERT INTO TB_TRAVEL_PLAN (USER_NICKNM, TITLE, DESCRIPTION, TRAVEL_START_DT, TRAVEL_END_DT, SPOT_COUNT, LIKE_COUNT, IS_PUBLIC)
VALUES ('RouteMate', '파리·런던 문화 여행', '유럽 대표 도시의 미술관과 랜드마크를 둘러보는 샘플 일정', '2026-10-03', '2026-10-05', 2, 0, 'Y');
SET @plan_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 1, '2026-10-03'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '파리 중심가 숙소', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='FR' AND r.REGION_CODE='PAR'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '09:30', '파리 미술관 관람', '루브르 박물관', '예약 시간을 확인합니다.', 1);
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 2, '2026-10-04'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '런던 지하철 이용', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='GB' AND r.REGION_CODE='LON'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '10:00', '런던 랜드마크 투어', '빅벤·타워 브리지', '오이스터 카드 또는 컨택리스 결제.', 1);

INSERT INTO TB_TRAVEL_PLAN (USER_NICKNM, TITLE, DESCRIPTION, TRAVEL_START_DT, TRAVEL_END_DT, SPOT_COUNT, LIKE_COUNT, IS_PUBLIC)
VALUES ('RouteMate', '베트남 푸꾸옥 휴양 일정', '푸꾸옥 해변과 야시장 중심의 여유로운 샘플 일정', '2026-11-01', '2026-11-03', 2, 0, 'Y');
SET @plan_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 1, '2026-11-01'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '해변 리조트 체크인', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='VN' AND r.REGION_CODE='PQC'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '14:00', '리조트 체크인과 해변 휴식', '롱비치', '공항 픽업을 미리 예약합니다.', 1);
INSERT INTO TB_TRAVEL_DAY (PLAN_ID, DAY_NO, PLAN_DATE) VALUES (@plan_id, 2, '2026-11-02'); SET @day_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_DAY_REGION (DAY_ID, COUNTRY_ID, REGION_ID, REGION_NOTE, SORT_ORDER) SELECT @day_id, c.COUNTRY_ID, r.REGION_ID, '선셋 시간 확인', 1 FROM TB_COUNTRY c JOIN TB_REGION r ON r.COUNTRY_ID = c.COUNTRY_ID WHERE c.COUNTRY_CODE='VN' AND r.REGION_CODE='PQC'; SET @day_region_id = LAST_INSERT_ID();
INSERT INTO TB_TRAVEL_SCHEDULE (DAY_REGION_ID, SCHEDULE_TIME, TITLE, LOCATION, MEMO, SORT_ORDER) VALUES (@day_region_id, '17:00', '푸꾸옥 야시장 방문', '즈엉동 야시장', '현지 음식과 기념품을 즐깁니다.', 1);
