CREATE TABLE TB_ADMIN_DEPT (
    DEPT_ID BIGINT NOT NULL AUTO_INCREMENT,
    DEPT_CODE VARCHAR(50) NOT NULL,
    DEPT_NAME VARCHAR(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_DEPT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UK_ADMIN_DEPT_CODE UNIQUE (DEPT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_ROLE (
    ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_CODE VARCHAR(50) NOT NULL,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ROLE_LEVEL INT NOT NULL,
    DEPT_ID BIGINT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ADMIN_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT FK_ADMIN_ROLE_DEPT FOREIGN KEY (DEPT_ID) REFERENCES TB_ADMIN_DEPT(DEPT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_PERMISSION (
    PERMISSION_ID BIGINT NOT NULL AUTO_INCREMENT,
    PERMISSION_CODE VARCHAR(100) NOT NULL,
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_PERMISSION PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_ADMIN_PERMISSION_CODE UNIQUE (PERMISSION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_MENU (
    MENU_ID BIGINT NOT NULL AUTO_INCREMENT,
    MENU_CODE VARCHAR(100) NOT NULL,
    MENU_NAME VARCHAR(100) NOT NULL,
    PARENT_MENU_ID BIGINT NULL,
    MENU_PATH VARCHAR(200),
    SORT_ORDER INT NOT NULL DEFAULT 0,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT UK_ADMIN_MENU_CODE UNIQUE (MENU_CODE),
    CONSTRAINT FK_ADMIN_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID) REFERENCES TB_ADMIN_MENU(MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_ROLE_PERMISSION (
    ROLE_PERMISSION_ID BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    ALLOW_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_ROLE_PERMISSION PRIMARY KEY (ROLE_PERMISSION_ID),
    CONSTRAINT UK_ADMIN_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ADMIN_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ADMIN_ROLE(ROLE_ID),
    CONSTRAINT FK_ADMIN_RP_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES TB_ADMIN_PERMISSION(PERMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_ROLE_MENU (
    ROLE_MENU_ID BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_ID BIGINT NOT NULL,
    MENU_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NULL,
    ALLOW_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_ROLE_MENU PRIMARY KEY (ROLE_MENU_ID),
    CONSTRAINT UK_ADMIN_ROLE_MENU UNIQUE (ROLE_ID, MENU_ID),
    CONSTRAINT FK_ADMIN_RM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ADMIN_ROLE(ROLE_ID),
    CONSTRAINT FK_ADMIN_RM_MENU FOREIGN KEY (MENU_ID) REFERENCES TB_ADMIN_MENU(MENU_ID),
    CONSTRAINT FK_ADMIN_RM_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES TB_ADMIN_PERMISSION(PERMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TB_ADMIN_USER_ROLE (
    USER_ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_ADMIN_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT UK_ADMIN_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_ADMIN_UR_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER_MSTR(USER_ID),
    CONSTRAINT FK_ADMIN_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ADMIN_ROLE(ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO TB_ADMIN_DEPT (DEPT_CODE, DEPT_NAME, USE_YN)
SELECT 'COMMON', '공통 운영', 'Y' WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_DEPT WHERE DEPT_CODE = 'COMMON');

INSERT INTO TB_ADMIN_ROLE (ROLE_CODE, ROLE_NAME, ROLE_LEVEL, DEPT_ID, USE_YN)
SELECT v.ROLE_CODE, v.ROLE_NAME, v.ROLE_LEVEL, d.DEPT_ID, 'Y'
FROM (SELECT 'ADMIN' ROLE_CODE, '최고 관리자' ROLE_NAME, 100 ROLE_LEVEL UNION ALL SELECT 'MASTER', '마스터 관리자', 80 UNION ALL SELECT 'SENIOR', '시니어 관리자', 60 UNION ALL SELECT 'JUNIOR', '주니어 관리자', 40) v
JOIN TB_ADMIN_DEPT d ON d.DEPT_CODE = 'COMMON'
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE r WHERE r.ROLE_CODE = v.ROLE_CODE);

INSERT INTO TB_ADMIN_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, USE_YN)
SELECT v.PERMISSION_CODE, v.PERMISSION_NAME, 'Y'
FROM (SELECT 'DASHBOARD_VIEW' PERMISSION_CODE, '대시보드 조회' PERMISSION_NAME UNION ALL SELECT 'MEMBER_VIEW', '회원 조회' UNION ALL SELECT 'MEMBER_STATUS_UPDATE', '회원 상태 변경' UNION ALL SELECT 'STAFF_VIEW', '직원 조회' UNION ALL SELECT 'STAFF_MANAGE', '직원 관리' UNION ALL SELECT 'PLAN_MANAGE', '여행 일정 관리' UNION ALL SELECT 'DESTINATION_MANAGE', '추천 여행지 관리') v
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_PERMISSION p WHERE p.PERMISSION_CODE = v.PERMISSION_CODE);

INSERT INTO TB_ADMIN_MENU (MENU_CODE, MENU_NAME, MENU_PATH, SORT_ORDER, USE_YN)
SELECT v.MENU_CODE, v.MENU_NAME, v.MENU_PATH, v.SORT_ORDER, 'Y'
FROM (SELECT 'DASHBOARD' MENU_CODE, '대시보드' MENU_NAME, '/admin' MENU_PATH, 10 SORT_ORDER UNION ALL SELECT 'MEMBERS', '회원 관리', '/admin/users', 20 UNION ALL SELECT 'STAFF', '직원 관리', '/admin/staff', 30 UNION ALL SELECT 'PLANS', '여행 일정 관리', '/admin/plans', 40 UNION ALL SELECT 'DESTINATIONS', '추천 여행지 관리', '/admin/destinations', 50) v
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_MENU m WHERE m.MENU_CODE = v.MENU_CODE);

INSERT INTO TB_ADMIN_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, ALLOW_YN)
SELECT r.ROLE_ID, p.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE r CROSS JOIN TB_ADMIN_PERMISSION p
WHERE (r.ROLE_CODE = 'ADMIN'
   OR (r.ROLE_CODE = 'MASTER' AND p.PERMISSION_CODE IN ('DASHBOARD_VIEW','MEMBER_VIEW','MEMBER_STATUS_UPDATE','STAFF_VIEW','PLAN_MANAGE','DESTINATION_MANAGE'))
   OR (r.ROLE_CODE = 'SENIOR' AND p.PERMISSION_CODE IN ('DASHBOARD_VIEW','MEMBER_VIEW','PLAN_MANAGE'))
   OR (r.ROLE_CODE = 'JUNIOR' AND p.PERMISSION_CODE = 'DASHBOARD_VIEW'))
  AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_PERMISSION x WHERE x.ROLE_ID = r.ROLE_ID AND x.PERMISSION_ID = p.PERMISSION_ID);

INSERT INTO TB_ADMIN_ROLE_MENU (ROLE_ID, MENU_ID, PERMISSION_ID, ALLOW_YN)
SELECT r.ROLE_ID, m.MENU_ID, p.PERMISSION_ID, 'Y'
FROM TB_ADMIN_ROLE r
JOIN TB_ADMIN_MENU m ON (r.ROLE_CODE = 'ADMIN' OR (r.ROLE_CODE IN ('MASTER','SENIOR') AND m.MENU_CODE IN ('DASHBOARD','MEMBERS','PLANS')) OR (r.ROLE_CODE = 'MASTER' AND m.MENU_CODE IN ('STAFF','DESTINATIONS')) OR (r.ROLE_CODE = 'JUNIOR' AND m.MENU_CODE = 'DASHBOARD'))
JOIN TB_ADMIN_PERMISSION p ON p.PERMISSION_CODE = CASE m.MENU_CODE WHEN 'DASHBOARD' THEN 'DASHBOARD_VIEW' WHEN 'MEMBERS' THEN 'MEMBER_VIEW' WHEN 'STAFF' THEN 'STAFF_VIEW' WHEN 'PLANS' THEN 'PLAN_MANAGE' ELSE 'DESTINATION_MANAGE' END
WHERE NOT EXISTS (SELECT 1 FROM TB_ADMIN_ROLE_MENU x WHERE x.ROLE_ID = r.ROLE_ID AND x.MENU_ID = m.MENU_ID);

INSERT INTO TB_ADMIN_USER_ROLE (USER_ID, ROLE_ID, PRIMARY_YN)
SELECT u.USER_ID, r.ROLE_ID, 'Y'
FROM TB_USER_MSTR u JOIN TB_ADMIN_ROLE r ON r.ROLE_CODE = u.USER_ROLE
WHERE u.USER_ROLE IN ('ADMIN','MASTER','SENIOR','JUNIOR')
  AND NOT EXISTS (SELECT 1 FROM TB_ADMIN_USER_ROLE x WHERE x.USER_ID = u.USER_ID AND x.ROLE_ID = r.ROLE_ID);
