CREATE TABLE TB_DEST_RECOMMEND (
    RECOMMEND_ID BIGINT NOT NULL AUTO_INCREMENT,
    DEST_ID BIGINT NOT NULL,
    DISPLAY_START_DT DATETIME(6) NOT NULL,
    DISPLAY_END_DT DATETIME(6) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 1,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_DEST_RECOMMEND PRIMARY KEY (RECOMMEND_ID),
    CONSTRAINT FK_DEST_RECOMMEND_DEST FOREIGN KEY (DEST_ID) REFERENCES TB_DESTINATION(DEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IX_DEST_RECOMMEND_PERIOD ON TB_DEST_RECOMMEND (USE_YN, DISPLAY_START_DT, DISPLAY_END_DT, SORT_ORDER);
