package com.trip.routemate.destination;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import static org.assertj.core.api.Assertions.assertThat;

class PlaceSeedMigrationTest {

    @Test
    void mysqlSeed_insertsOneHundredLinkedPlacesWithoutDuplicates() throws Exception {
        verifySeed("jdbc:h2:mem:place_seed_mysql;MODE=MySQL;DB_CLOSE_DELAY=-1", "mysql");
    }

    @Test
    void oracleSeed_insertsOneHundredLinkedPlacesWithoutDuplicates() throws Exception {
        verifySeed("jdbc:h2:mem:place_seed_oracle;MODE=Oracle;DB_CLOSE_DELAY=-1", "oracle");
    }

    private void verifySeed(String jdbcUrl, String database) throws Exception {
        try (var connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            createPlaceSchema(connection);
            execute(connection, "db/migration/" + database + "/V2__seed_travel_locations.sql");
            execute(connection, "db/migration/" + database + "/V3__add_phu_quoc.sql");
            execute(connection, "db/migration/" + database + "/V12__seed_places.sql");

            assertThat(queryForLong(connection, "SELECT COUNT(*) FROM TB_DESTINATION")).isEqualTo(100);
            assertThat(queryForLong(connection, "SELECT COUNT(DISTINCT COUNTRY_ID) FROM TB_DESTINATION")).isEqualTo(15);
            assertThat(queryForLong(connection, "SELECT COUNT(DISTINCT CATEGORY) FROM TB_DESTINATION")).isEqualTo(8);
            assertThat(queryForLong(connection, "SELECT COUNT(*) FROM TB_DESTINATION d JOIN TB_REGION r ON r.REGION_ID = d.REGION_ID WHERE r.COUNTRY_ID <> d.COUNTRY_ID")).isZero();

            execute(connection, "db/migration/" + database + "/V12__seed_places.sql");
            assertThat(queryForLong(connection, "SELECT COUNT(*) FROM TB_DESTINATION")).isEqualTo(100);
        }
    }

    private void createPlaceSchema(Connection connection) throws SQLException {
        try (var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE TB_COUNTRY (
                        COUNTRY_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        COUNTRY_NAME VARCHAR(50) NOT NULL,
                        COUNTRY_CODE VARCHAR(10) NOT NULL UNIQUE,
                        COUNTRY_STAT_CD VARCHAR(20) NOT NULL,
                        CREATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE TB_REGION (
                        REGION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        COUNTRY_ID BIGINT NOT NULL,
                        REGION_NAME VARCHAR(50) NOT NULL,
                        REGION_CODE VARCHAR(20) NOT NULL,
                        SORT_ORDER INT NOT NULL,
                        REGION_STAT_CD VARCHAR(20) NOT NULL,
                        CREATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        UNIQUE (COUNTRY_ID, REGION_CODE),
                        FOREIGN KEY (COUNTRY_ID) REFERENCES TB_COUNTRY (COUNTRY_ID)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE TB_DESTINATION (
                        DEST_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        DEST_NAME VARCHAR(100) NOT NULL,
                        DEST_DESC CLOB,
                        COUNTRY_ID BIGINT NOT NULL,
                        REGION_ID BIGINT NOT NULL,
                        CATEGORY VARCHAR(30) NOT NULL,
                        IMAGE_URL VARCHAR(500),
                        MAP_LAT DOUBLE PRECISION NOT NULL,
                        MAP_LNG DOUBLE PRECISION NOT NULL,
                        LIKE_COUNT INT NOT NULL,
                        CREATE_DT TIMESTAMP NOT NULL,
                        FOREIGN KEY (COUNTRY_ID) REFERENCES TB_COUNTRY (COUNTRY_ID),
                        FOREIGN KEY (REGION_ID) REFERENCES TB_REGION (REGION_ID)
                    )
                    """);
        }
    }

    private void execute(Connection connection, String resourcePath) {
        ScriptUtils.executeSqlScript(connection, new ClassPathResource(resourcePath));
    }

    private long queryForLong(Connection connection, String sql) throws SQLException {
        try (var statement = connection.createStatement(); ResultSet resultSet = statement.executeQuery(sql)) {
            resultSet.next();
            return resultSet.getLong(1);
        }
    }
}
