import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { hasPermission } from '../../features/admin/permissions';
import { useAuth } from '../../hooks/useAuth';
import { SearchableSelect } from '../../components/SearchableSelect';
import { CustomCalendar } from '../../components/CustomCalendar';
import { StyledSelect } from '../../components/StyledSelect';

type Status = 'Y' | 'N';
type Country = { countryId: number; countryName: string; countryCode: string; countryStatCd: string; regionCount: number };
type Region = { regionId: number; regionName: string; regionCode: string; sortOrder: number; regionStatCd: string };
type Recommendation = { recommendId: number; destinationId: number; countryId: number; regionId: number; destinationName: string; countryName: string; regionName: string; imageUrl: string | null; displayStartDt: string; displayEndDt: string; sortOrder: number; useYn: Status };
type Form = { countryId: string; regionId: string; imageUrl: string; startDate: string; startTime: string; endDate: string; endTime: string; sortOrder: number; useYn: Status };
const emptyForm: Form = { countryId: '', regionId: '', imageUrl: '', startDate: '', startTime: '00:00', endDate: '', endTime: '23:59', sortOrder: 1, useYn: 'Y' };
const formatDate = (value: string) => new Intl.DateTimeFormat('ko-KR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export const AdminRecommendations = () => {
  const navigate = useNavigate(); const { user } = useAuth(); const canManage = hasPermission(user, 'DESTINATION_MANAGE');
  const [data, setData] = useState<{ recommendations: Recommendation[] } | null>(null); const [countries, setCountries] = useState<Country[]>([]); const [regions, setRegions] = useState<Region[]>([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (user && !canManage) navigate('/admin', { replace: true }); }, [canManage, navigate, user]);
  const load = useCallback(async () => { setLoading(true); try { const [recommendations, countryResponse] = await Promise.all([axios.get<{ recommendations: Recommendation[] }>('/api/admin/recommendations'), axios.get<{ countries: Country[] }>('/api/admin/destinations/countries', { params: { status: 'ACTIVE' } })]); setData(recommendations.data); setCountries(countryResponse.data.countries); } catch { setError('추천 정보를 불러오지 못했습니다.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const loadRegions = async (countryId: string) => { setRegions([]); if (!countryId) return; try { const response = await axios.get<Region[]>(`/api/admin/destinations/countries/${countryId}/regions`); setRegions(response.data.filter((region) => region.regionStatCd === 'ACTIVE')); } catch { setError('지역 정보를 불러오지 못했습니다.'); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const start = `${form.startDate}T${form.startTime}`; const end = `${form.endDate}T${form.endTime}`; if (!form.startDate || !form.endDate || new Date(start) >= new Date(end)) { setError('종료일시는 시작일시보다 늦어야 합니다.'); return; } setSaving(true); setError(null); try { const payload = { countryId: Number(form.countryId), regionId: Number(form.regionId), imageUrl: form.imageUrl || null, displayStartDt: start, displayEndDt: end, sortOrder: form.sortOrder, useYn: form.useYn }; if (editingId) await axios.patch(`/api/admin/recommendations/${editingId}`, payload); else await axios.post('/api/admin/recommendations', payload); setForm(emptyForm); setRegions([]); setEditingId(null); await load(); } catch (e) { setError(axios.isAxiosError(e) ? e.response?.data?.detail || '추천 정보를 저장하지 못했습니다.' : '추천 정보를 저장하지 못했습니다.'); } finally { setSaving(false); } };
  const edit = (item: Recommendation) => { const start = item.displayStartDt.slice(0, 16); const end = item.displayEndDt.slice(0, 16); const countryId = String(item.countryId); setEditingId(item.recommendId); setForm({ countryId, regionId: String(item.regionId), imageUrl: item.imageUrl ?? '', startDate: start.slice(0, 10), startTime: start.slice(11, 16), endDate: end.slice(0, 10), endTime: end.slice(11, 16), sortOrder: item.sortOrder, useYn: item.useYn }); void loadRegions(countryId); };
  const cancelEdit = () => { setEditingId(null); setForm(emptyForm); setRegions([]); setError(null); };
  return <>
    <header><p className="text-xs font-bold tracking-[0.2em] text-indigo-300">RECOMMENDATION MANAGEMENT</p><h1 className="mt-2 text-3xl font-extrabold text-white">추천 여행지 관리</h1><p className="mt-2 text-sm text-slate-500">홈페이지에 노출할 지역과 기간을 설정하고 대표이미지를 등록합니다.</p></header>
    {error ? <p role="alert" className="mt-5 rounded-2xl border border-rose-400/15 bg-rose-400/5 px-4 py-3 text-sm text-rose-200">{error}</p> : null}
    <section className="mt-7 rounded-[24px] border border-white/10 bg-white/[0.03] p-5 sm:p-7">
      <div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[0.16em] text-indigo-300">{editingId ? 'EDIT' : 'NEW'}</p><h2 className="mt-1 text-xl font-bold text-white">{editingId ? '추천 설정 수정' : '추천 여행지 등록'}</h2></div>{editingId ? <button type="button" onClick={cancelEdit} className="text-xs text-slate-500">수정 취소</button> : null}</div>
      <form onSubmit={(event) => void save(event)} className="mt-6 space-y-6">
        <div><p className="mb-3 text-sm font-bold text-slate-200">1. 노출 지역</p><div className="grid gap-3 md:grid-cols-2"><SearchableSelect value={form.countryId} options={countries.map((x) => ({ value: String(x.countryId), label: x.countryName, hint: x.countryCode }))} placeholder="국가를 검색하세요" onChange={(value) => { setForm((v) => ({ ...v, countryId: value, regionId: '' })); void loadRegions(value); }} /><SearchableSelect value={form.regionId} options={regions.map((x) => ({ value: String(x.regionId), label: x.regionName, hint: x.regionCode }))} placeholder={form.countryId ? '지역을 검색하세요' : '국가를 먼저 선택하세요'} disabled={!form.countryId} onChange={(value) => setForm((v) => ({ ...v, regionId: value }))} /></div></div>
        <div><p className="mb-3 text-sm font-bold text-slate-200">2. 노출 기간</p><div className="grid gap-3 rounded-2xl border border-white/10 bg-slate-950/30 p-4 md:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-slate-400">시작일자</p><div className="grid grid-cols-[1fr_130px] gap-2"><CustomCalendar value={form.startDate} onChange={(value) => setForm((v) => ({ ...v, startDate: value }))} placeholder="시작 날짜" /><input required type="time" value={form.startTime} onChange={(e) => setForm((v) => ({ ...v, startTime: e.target.value }))} className="h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-xs text-slate-300" /></div></div><div><p className="mb-2 text-xs font-semibold text-slate-400">종료일자</p><div className="grid grid-cols-[1fr_130px] gap-2"><CustomCalendar value={form.endDate} onChange={(value) => setForm((v) => ({ ...v, endDate: value }))} placeholder="종료 날짜" /><input required type="time" value={form.endTime} onChange={(e) => setForm((v) => ({ ...v, endTime: e.target.value }))} className="h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-xs text-slate-300" /></div></div></div></div>
        <div><p className="mb-3 text-sm font-bold text-slate-200">3. 대표이미지</p><div className="grid gap-4 md:grid-cols-[1fr_260px]"><input value={form.imageUrl} onChange={(e) => setForm((v) => ({ ...v, imageUrl: e.target.value }))} placeholder="이미지 URL을 입력하세요 (선택)" className="h-11 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm text-slate-300" />{form.imageUrl ? <img src={form.imageUrl} alt="대표이미지 미리보기" className="h-32 w-full rounded-xl object-cover" /> : <div className="flex h-32 items-center justify-center rounded-xl border border-dashed border-white/10 text-xs text-slate-600">이미지 미리보기</div>}</div></div>
        <div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-semibold text-slate-400">노출 순위<input required min={1} type="number" value={form.sortOrder} onChange={(e) => setForm((v) => ({ ...v, sortOrder: Number(e.target.value) }))} className="mt-1 h-11 rounded-xl border border-white/10 bg-slate-950 px-3 text-sm text-white" /></label><label className="grid gap-1 text-xs font-semibold text-slate-400">상태<StyledSelect value={form.useYn} onChange={(value) => setForm((v) => ({ ...v, useYn: value as Status }))} ariaLabel="추천 상태" options={[{ value: 'Y', label: '활성', icon: 'fa-circle-check' }, { value: 'N', label: '비활성', icon: 'fa-circle-pause' }]} className="mt-1" /></label></div>
        <button type="submit" disabled={saving || loading || !form.countryId || !form.regionId} className="h-12 w-full rounded-xl bg-indigo-500 text-sm font-bold text-white transition hover:bg-indigo-400 disabled:opacity-50">{saving ? '저장 중...' : editingId ? '수정 저장' : '추천 등록'}</button>
      </form>
    </section>
    <section className="mt-6 overflow-x-auto rounded-[24px] border border-white/10 bg-white/[0.03] p-5"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-white/10 text-xs text-slate-600"><tr><th className="px-3 py-3">국가·지역</th><th className="px-3 py-3">대표 여행지</th><th className="px-3 py-3">노출 기간</th><th className="px-3 py-3">순위</th><th className="px-3 py-3 text-right">관리</th></tr></thead><tbody className="divide-y divide-white/5">{data?.recommendations.map((item) => <tr key={item.recommendId}><td className="px-3 py-4 text-sm text-slate-200">{item.countryName} · {item.regionName}</td><td className="px-3 py-4 text-sm text-slate-400">{item.destinationName}</td><td className="px-3 py-4 text-xs text-slate-500">{formatDate(item.displayStartDt)} ~ {formatDate(item.displayEndDt)}</td><td className="px-3 py-4 text-xs text-indigo-300">TOP {item.sortOrder}</td><td className="px-3 py-4 text-right"><button type="button" onClick={() => edit(item)} className="text-xs font-semibold text-indigo-300">수정</button></td></tr>)}</tbody></table></section>
  </>;
};
