import { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';

const empty = { partnerName: '', businessNumber: '', representativeName: '', managerName: '', managerEmail: '', managerPhone: '', websiteUrl: '', commissionRate: '12', contractStartDate: '', contractEndDate: '', memo: '', ownerLoginId: '', ownerPassword: '', ownerName: '' };

export const AdminPartnerOnboarding = () => {
  const navigate = useNavigate(); const [form, setForm] = useState(empty); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const update = (key: keyof typeof empty, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await axios.post('/api/admin/partners', { ...form, partnerCode: null, commissionRate: Number(form.commissionRate), contractStartDate: form.contractStartDate || null, contractEndDate: form.contractEndDate || null, websiteUrl: form.websiteUrl || null, memo: form.memo || null, partnerStatus: 'ACTIVE' }); navigate('/admin/partners', { replace: true }); } catch (e) { setError(axios.isAxiosError(e) ? e.response?.data?.detail ?? '파트너사 등록에 실패했습니다.' : '파트너사 등록에 실패했습니다.'); } finally { setSaving(false); } };
  const cls = 'h-11 rounded-xl border border-white/10 bg-slate-950 px-3 text-sm text-white outline-none focus:border-indigo-400';
  const field = (label: string, key: keyof typeof empty, type = 'text', required = false) => <label className="grid gap-2 text-xs text-slate-400">{label}<input type={type} required={required} value={form[key]} onChange={(e) => update(key, e.target.value)} className={cls} /></label>;
  return <main className="mx-auto w-full max-w-4xl p-6 sm:p-10"><Link to="/admin/partners" className="text-sm font-bold text-indigo-300">← 파트너사 목록</Link><p className="mt-8 text-xs font-bold tracking-[.18em] text-indigo-300">ADMIN ONLY</p><h1 className="mt-3 text-3xl font-extrabold text-white">파트너사 및 대표 직원 등록</h1><p className="mt-2 text-sm text-slate-500">파트너 코드는 자동 생성됩니다.</p><form onSubmit={(e) => void submit(e)} className="mt-7 grid gap-5 rounded-2xl border border-white/10 bg-white/[.03] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-bold text-indigo-200">사업자·계약 정보</h2>{field('파트너사명', 'partnerName', 'text', true)}{field('사업자등록번호', 'businessNumber', 'text', true)}{field('대표자명', 'representativeName', 'text', true)}{field('수수료율(%)', 'commissionRate', 'number', true)}{field('계약 시작일', 'contractStartDate', 'date')}{field('계약 종료일', 'contractEndDate', 'date')}{field('웹사이트', 'websiteUrl', 'url')}<span /><h2 className="sm:col-span-2 font-bold text-indigo-200">운영 담당자</h2>{field('담당자명', 'managerName', 'text', true)}{field('담당자 이메일', 'managerEmail', 'email', true)}{field('담당자 연락처', 'managerPhone', 'text', true)}{field('관리 메모', 'memo')}<h2 className="sm:col-span-2 font-bold text-indigo-200">대표 직원 계정</h2>{field('대표 직원 이름', 'ownerName', 'text', true)}{field('대표 직원 ID', 'ownerLoginId', 'email', true)}{field('대표 직원 초기 비밀번호', 'ownerPassword', 'password', true)}{error ? <p className="sm:col-span-2 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p> : null}<button disabled={saving} className="h-11 rounded-xl bg-indigo-500 text-sm font-bold text-white sm:col-span-2">{saving ? '등록 중...' : '파트너사와 대표 직원 등록'}</button></form></main>;
};
